import { iconFor } from "./_icons";
import"./ditto.css";
import Logo from"./components/logo";
import ListRow from"./components/list-row";
import MediaCard from"./components/media-card";
import MediaTile from"./components/media-tile";
import MediaCard2 from"./components/media-card2";
import ListRow2 from"./components/list-row2";
import ListRow3 from"./components/list-row3";
import ListRow4 from"./components/list-row4";
import ListRow5 from"./components/list-row5";
import Logo2 from"./components/logo2";
import ListRow6 from"./components/list-row6";
import Logo3 from"./components/logo3";
// Generated by clone-site. Do not edit by hand.
const Logo_data = [
    { ariaLabel:"View previous offer" },
    { ariaLabel:"View next offer" },
    { ariaLabel:"Pause offer carousel" }
];
const ListRow_data = [
    { href:"/our-journey", label:"About" },
    { href:"/juice-subscription-membership/signup", label:"Pressed Rewards" },
    { href:"/juice-bar-locations", label:"Find a Store" },
    { href:"/flavor-quiz", label:"Quiz" },
    { href:"/catering", label:"Catering" }
];
const MediaCard_data = [
    { imgSrc:"/assets/cloned/images/7b0e822a13b6.webp", href:"https://pressed.com/products/1-day-reset-cleanse-kit", title:"1-Day Reset Cleanse", text:"72.00", text2:"63.00" },
    { imgSrc:"/assets/cloned/images/0a08677c94fa.webp", href:"https://pressed.com/products/2-day-pro-detox-juice-cleanse", title:"2-Day Pro Cleanse+", text:"190.00", text2:"165.00" },
    { imgSrc:"/assets/cloned/images/2f01809f4480.webp", href:"https://pressed.com/products/best-selling-cold-pressed-juices-pack", title:"Best-Selling Wellness Starter Pack", text:"35.00", text2:"30.00" },
    { imgSrc:"/assets/cloned/images/df95cb4530ee.webp", href:"https://pressed.com/products/express-half-day-juice-cleanse", title:"Express Half-Day Cleanse", text:"27.00", text2:"22.00" },
    { imgSrc:"/assets/cloned/images/f9c0f13e1c19.webp", href:"https://pressed.com/products/protein-acai-bowl", title:"Acai Protein Bowl", text:"13.95", text2:"12.95" },
    { imgSrc:"/assets/cloned/images/e69e42a2fa1c.webp", href:"https://pressed.com/products/detox-half-day-fast", title:"Detox Half-Day Juice Cleanse", text:"30.00", text2:"25.00" },
    { imgSrc:"/assets/cloned/images/c15de451cad3.webp", href:"https://pressed.com/products/beet-apple-ginger-juice", title:"Daily Roots 3: Ginger Juice", text:"6.95", text2:"5.50" },
    { imgSrc:"/assets/cloned/images/863324569d01.webp", href:"https://pressed.com/products/disney-descendants-wicked-wonderland-bundle", title:"Disney Descendants 6-Pack", text:"35.00", text2:"30.00" },
    { imgSrc:"/assets/cloned/images/976d5e44cda7.webp", href:"https://pressed.com/products/kale-apple-lemon-juice", title:"Daily Greens 2: Sweet Apple Juice", text:"6.95", text2:"5.50" },
    { imgSrc:"/assets/cloned/images/7a7aed18b66e.webp", href:"https://pressed.com/products/simple-cleanse-gut-health-pack", title:"Cleanse + Probiotic Ritual: 7-Day Simple Cleanse® + Gut Health", text:"60.00", text2:"55.00" }
];
const MediaTile_data = [
    { imgSrc:"/assets/cloned/images/539afc6d6c63.jpg", label:"Detox and Reset" },
    { imgSrc:"/assets/cloned/images/d89ba340927e.webp", label:"Gut Health" },
    { imgSrc:"/assets/cloned/images/08d68e68d71f.jpg", label:"Immunity" },
    { imgSrc:"/assets/cloned/images/3b2bf7e8995e.jpg", label:"Hydration and Recovery" }
];
const MediaCard2_data = [
    { imgSrc:"/assets/cloned/images/7b8a529ef56b.webp", title:"Cold-Pressed Juices", description:"$6.95", description2:"$5.50 VIP", label:"Shop Cold-Pressed Juices" },
    { imgSrc:"/assets/cloned/images/a61c043596ce.webp", title:"Wellness Shots", description:"$3.75", description2:"$3.25 VIP", label:"Shop Wellness Shots" },
    { imgSrc:"/assets/cloned/images/9bd9d40c6e70.webp", title:"Fruit and Protein Smoothies", description:"$6.95", description2:"$5.50 VIP", label:"Shop Smoothies" },
    { imgSrc:"/assets/cloned/images/ba8622911c50.webp", title:"Non-Dairy Almond Milk", description:"$6.95", description2:"$5.50 VIP", label:"Shop Almond Milk" },
    { imgSrc:"/assets/cloned/images/847be0bcf7bf.webp", title:"Freeze Dairy-Free Soft Serve", description:"$6.95", description2:"$5.50 VIP", label:"Shop Freeze" },
    { imgSrc:"/assets/cloned/images/62d5a6515b98.webp", title:"Acai and Smoothie Bowls", description:"$11.95", description2:"$10.95 VIP", label:"Shop Smoothie Bowls" }
];
const ListRow2_data = [
    { href:"/shop", label:"Shop All" },
    { href:"/juice-bar-locations", label:"Find a Store" },
    { href:"https://pressed.com/foodservice", label:"Wholesale" },
    { href:"/catering", label:"Catering" }
];
const ListRow3_data = [
    { href:"/our-journey", label:"Our Story" },
    { href:"https://pressed.com/blogs/pressed-life", label:"Blog" },
    { href:"https://pressed.com/juice-cleanses", label:"Juice Cleanses" },
    { href:"https://pressed.com/acai-bowls", label:"Acai Bowls" },
    { href:"https://pressed.com/cleanse-guide", label:"Cleanse Guide" },
    { href:"/juice-subscription-membership/signup", label:"Rewards" },
    { href:"https://pressed.com/gut-biome-sulforaphane-benefits", label:"Gut Biome+" }
];
const ListRow4_data = [
    { href:"https://pressed.com/pages/contact-us", label:"Contact Us" },
    { href:"https://pressed.com/faqs", label:"FAQs" },
    { href:"https://pressed.com/allergens", label:"Nutrition" },
    { href:"https://pressed.com/careers", label:"Careers" }
];
const ListRow5_data = [
    { href:"https://pressed.com/legal/shipping-policy", label:"Shipping & Delivery" },
    { href:"https://pressed.com/legal/refund-and-cancellation-policy", label:"Refund & Cancellation" },
    { href:"https://pressed.com/legal/member-terms-and-conditions", label:"Member Terms and Conditions" },
    { href:"https://pressed.com/legal/vip-terms-and-conditions", label:"VIP Terms and Conditions" },
    { href:"https://pressed.com/legal/accessibility-policy", label:"Accessibility Policy" }
];
const Logo2_data = [
    { href:"https://www.instagram.com/pressedjuicery/", alt:"Instagram" },
    { href:"https://www.facebook.com/PressedOfficial", alt:"Facebook" },
    { href:"https://x.com/pressedjuicery", alt:"Twitter" },
    { href:"https://www.youtube.com/channel/UC5E5Wd9hZaZoyJU25cKeRsg", alt:"YouTube" }
];
const ListRow6_data = [
    { href:"https://pressed.com/legal/terms-of-use", label:"Terms of Use" },
    { href:"https://pressed.com/legal/privacy-policy", label:"Privacy Policy" },
    { href:"javascript:Cookiebot.show()", label:"Do Not Sell or Share My Personal Information" }
];
const Logo3_data = [
    { href:"https://www.instagram.com/pressedjuicery/", alt:"Instagram" },
    { href:"https://www.facebook.com/PressedOfficial", alt:"Facebook" },
    { href:"https://x.com/pressedjuicery", alt:"Twitter" },
    { href:"https://www.youtube.com/channel/UC5E5Wd9hZaZoyJU25cKeRsg", alt:"YouTube" }
];
const Logo_meta: string[][] = [
    ["style-link-9","n15"],
    ["style-div-3","n17"],
    ["style-div-4","n19"]
];
const ListRow_meta: string[][] = [
    ["n33","style-pressed-juicery-home-2"],
    ["n35","style-source"],
    ["n37","style-ul-3"],
    ["n39","style-div-5"],
    ["style-shop-dropdown-2","style-33"]
];
const MediaCard_meta: string[][] = [
    ["n106","motion-div-2","style-div-79","style-image-15","style-div-114","n111","style-div-94","style-h1","style-strong-38","style-div-115","style-div-95","style-div-29","n118"],
    ["style-div-116","style-div-96","style-a-5","style-u","style-br-65","n124","style-strong-39","n126","style-p-46","style-a","style-p-50","n130","style-h3-6"],
    ["style-div-30","style-div-27","style-p-38","style-figure-13","style-div-117","style-image-10","style-heading-3","style-strong-2","style-p-7","style-div-31","style-p-51","style-figure-12","style-div-22"],
    ["style-image-11","style-heading-22","style-strong-3","style-p-60","style-div-118","style-p-8","style-figure-2","style-div-32","style-image-4","style-heading-7","style-strong-40","style-p-9","style-link-2"],
    ["style-div-23","style-div-13","style-p-15","style-div-97","style-hr-2","style-div-33","style-p-16","style-div-14","style-div-128","style-heading-8","style-div-98","style-div-24","style-heading-2"],
    ["style-br-13","style-br","style-figure-4","style-div-15","style-link-14","style-image-3","style-p-17","style-strong-33","style-p-18","style-br-20","style-br-2","style-br-21","style-br-3"],
    ["style-link-3","style-br-4","style-p-19","style-div-16","style-heading-4","style-br-5","style-br-14","style-figure-3","style-div-25","style-link-15","style-image-6","style-p-23","style-strong-34"],
    ["style-p-20","style-br-6","style-br-15","style-br-7","style-br-16","style-link-4","style-br-17","style-p-10","style-div-26","n206","style-figure-14","n208","style-link-16"],
    ["style-image-16","style-p-11","style-strong-23","style-p-12","n214","style-br-8","style-br-72","style-br-9","style-link-5","style-br-29","n220","style-div-56","n222"],
    ["style-heading-10","style-heading-11","style-strong-24","n226","n227","style-p-24","style-br-35","style-br-22","style-div-151","style-heading-9","style-br-56","style-heading-5","style-strong-5"]
];
const MediaTile_meta: string[][] = [
    ["style-div-101","style-p-13","n254","n255","style-div-18"],
    ["style-p-35","style-heading-12","style-strong","style-p-37","style-div-80"],
    ["style-div-19","style-div-57","style-div-69","style-div-20","style-div-58"],
    ["style-heading-26","style-br-41","style-br-68","style-p-61","style-div-81"]
];
const MediaCard2_meta: string[][] = [
    ["n304","style-strong-20","style-br-42","style-p-36","n308","style-heading-15","n310","style-br-24","style-p-26"],
    ["n313","style-div-72","style-div-143","style-div-64","n317","style-div-65","n319","style-div-66","style-p-27"],
    ["style-div-67","style-div-82","style-heading-16","style-div-73","style-div-142","style-figure-9","style-div-134","style-link-18","style-image-9"],
    ["style-div-74","style-heading-21","style-strong-44","style-p-41","style-strong-45","style-br-43","style-br-70","style-br-44","style-strong-25"],
    ["style-br-45","style-br-51","style-br-46","style-strong-9","style-br-25","style-br-74","style-br-47","style-strong-48","style-br-48"],
    ["style-heading-30","style-strong-26","style-p-47","style-strong-27","style-br-26","style-link-19","style-br-38","style-link-20","style-u-2"]
];
const ListRow2_meta: string[][] = [
    ["n436","style-p-43"],
    ["n438","style-br-52"],
    ["style-strong-35","style-br-53"],
    ["style-strong-11","style-link-8"]
];
const ListRow3_meta: string[][] = [
    ["style-strong-50","style-strong-28"],
    ["n449","style-div-84"],
    ["n451","style-div-38"],
    ["style-div-153","style-div-85"],
    ["n455","style-div-86"],
    ["n457","style-h2-2"],
    ["style-p-56","style-p-44"]
];
const ListRow4_meta: string[][] = [
    ["style-a-9","style-strong-29"],
    ["n466","style-strong-30"],
    ["style-a-10","style-a-6"],
    ["n470","style-div-39"]
];
const ListRow5_meta: string[][] = [
    ["n475","style-h2-3"],
    ["n477","style-div-87"],
    ["n479","style-div-88"],
    ["n481","style-div-89"],
    ["n483","style-p-29"]
];
const Logo2_meta: string[][] = [
    ["style-img","style-h3","style-strong-47"],
    ["n499","style-p-58","n501"],
    ["n502","style-figure-15","n504"],
    ["n505","style-h3-8","style-strong-12"]
];
const ListRow6_meta: string[][] = [
    ["style-div-141","style-img-6"],
    ["n514","style-strong-31"],
    ["style-p-64","style-div-90"]
];
const Logo3_meta: string[][] = [
    ["style-figure-5","style-div-41","n521"],
    ["n522","style-strong-32","n524"],
    ["n525","style-p-45","style-figure-17"],
    ["n528","style-img-2","style-h3-10"]
];
const Logo_styles = [
    { className:"w-2 h-3" },
    { className:"w-2 h-3" },
    { className:"w-3.5 h-4" }
];
const MediaCard_styles = [
    { className2:"max-md:w-39 max-md:h-39 md:max-lg:w-44 md:max-lg:h-44", className4:"max-md:[font-family:regola-neue-medium,_sans-serif]", className5:"mt-6 max-md:mt-0", className6:"grow basis-0", className7:"grow basis-0" },
    { className2:"max-md:w-39 max-md:h-39 md:max-lg:w-44 md:max-lg:h-44", className4:"max-md:[font-family:regola-neue-medium,_sans-serif]", className5:"mt-12 max-md:mt-0 md:max-lg:mt-6", className6:"grow basis-0", className7:"grow basis-0" },
    { className2:"max-md:w-39 max-md:h-39 md:max-lg:w-44 md:max-lg:h-44", className4:"max-md:[font-family:regola-neue-medium,_sans-serif]", className6:"grow basis-0", className7:"grow basis-0" },
    { className:"max-md:hidden", className2:"md:max-lg:w-44 md:max-lg:h-44", className5:"mt-6", className6:"w-1/2", className7:"w-1/2" },
    { className:"max-md:block md:max-lg:hidden", className2:"max-md:w-39 max-md:h-39", className3:"max-md:inline", className4:"max-md:[font-family:regola-neue-medium,_sans-serif]", className5:"mt-12 max-md:mt-0", className6:"w-1/2", className7:"w-1/2" },
    { className:"max-md:block md:max-lg:hidden", className2:"max-md:w-39 max-md:h-39", className3:"max-md:inline", className4:"max-md:[font-family:regola-neue-medium,_sans-serif]", className5:"mt-12 max-md:mt-0", className6:"w-1/2", className7:"w-1/2" },
    { className:"max-md:block md:max-lg:hidden", className2:"max-md:w-39 max-md:h-39", className3:"max-md:inline", className4:"max-md:[font-family:regola-neue-medium,_sans-serif]", className5:"mt-12 max-md:mt-0", className6:"w-1/2", className7:"w-1/2" },
    { className:"max-md:block md:max-lg:hidden", className2:"max-md:w-39 max-md:h-39", className3:"max-md:inline", className4:"max-md:[font-family:regola-neue-medium,_sans-serif]", className5:"mt-12 max-md:mt-0", className6:"w-1/2", className7:"w-1/2" },
    { className:"max-md:block md:max-lg:hidden", className2:"max-md:w-39 max-md:h-39", className3:"max-md:inline", className4:"max-md:[font-family:regola-neue-medium,_sans-serif]", className5:"mt-12 max-md:mt-0", className6:"w-1/2", className7:"w-1/2" },
    { className:"max-md:block md:max-lg:hidden", className2:"max-md:w-39 max-md:h-39", className3:"max-md:inline", className4:"max-md:[font-family:regola-neue-medium,_sans-serif]", className6:"w-1/2", className7:"w-1/2" }
];
const ListRow2_styles = [
    { className:"pb-2" },
    { className:"pb-2" },
    { className:"pb-2" },
    {  }
];
const ListRow3_styles = [
    { className:"pb-2" },
    { className:"pb-2" },
    { className:"pb-2" },
    { className:"pb-2" },
    { className:"pb-2" },
    { className:"pb-2" },
    {  }
];
const ListRow4_styles = [
    { className:"pb-2" },
    { className:"pb-2" },
    { className:"pb-2" },
    {  }
];
const ListRow5_styles = [
    { className:"pb-2" },
    { className:"pb-2" },
    { className:"pb-2" },
    { className:"pb-2" },
    {  }
];
const Logo2_styles = [
    { className:"mr-4", className2:"max-lg:w-6 max-lg:h-6" },
    { className:"mr-4", className2:"max-lg:w-3 max-lg:h-6" },
    { className:"mr-4", className2:"max-lg:w-6 max-lg:h-5" },
    { className2:"max-lg:w-6 max-lg:h-4" }
];
const ListRow6_styles = [
    { className:"mr-6" },
    { className:"mr-6" },
    {  }
];
const Logo3_styles = [
    { className:"mr-4", className2:"w-6 h-6" },
    { className:"mr-4", className2:"w-3 h-6" },
    { className:"mr-4", className2:"w-6 h-5" },
    { className2:"w-6 h-4" }
];

export default function Page() {
  return (
    <>
      <div className="block" id="__nuxt">
        <div className="block">
          <div className="min-h-screen grid grid-cols-1">
            <div className="block" data-ditto-id="style-default-layout-header-wrapper" id="default-layout-header-wrapper">
              <a className="w-[244.828px] h-11.5 border-r border-solid border-r-color-002 border-b border-b-color-002 block absolute -top-12 z-101 pt-1.5 pb-0.5 px-1.5 overflow-hidden text-2xl leading-9 bg-background cursor-pointer" data-component="link" href="#maincontent">
                Skip to main content
              </a>
              <header className="h-[8.6875rem] block sticky top-0 z-100 max-md:h-[9.4375rem] md:max-lg:h-[8.1875rem]" data-ditto-id="style-pressed-header" id="pressed-header">
                <div className="min-h-10 block py-3 text-background [font-family:regola-neue-medium,_sans-serif] bg-foreground max-md:h-15 max-md:flex max-md:py-1 max-md:items-center">
                  <div className="block max-w-360 px-16 mx-auto max-md:px-6 md:max-lg:px-8" data-ditto-id="style-div-6">
                    <div className="flex justify-between items-center">
                      <div className="flex px-4 flex-wrap justify-center grow gap-1 text-center max-md:flex-col max-lg:items-center max-lg:[font-family:regola-neue-semibold,_sans-serif] max-lg:text-xs max-lg:leading-[1rem] max-md:gap-[initial]" aria-label="View all offers Carousel" aria-live="polite" role="region">
                        <span className="overflow-hidden line-clamp-1 max-md:line-clamp-3">
                          Free Local Delivery on Orders $60+
                        </span>
                        <span className="block ml-4 underline whitespace-nowrap cursor-pointer max-lg:ml-0" data-ditto-id="style-viewallofferselement" data-component="button" id="viewAllOffersElement" role="button">
                          {" View All Offers"}
                        </span>
                      </div>
                      <div className="flex shrink-0" data-ditto-id="style-div-7">
                        {Logo_data.map((d, i) => <Logo key={i} d={d} styles={Logo_styles[i]} />)}
                      </div>
                    </div>
                  </div>
                </div>
                <div className="block py-6 px-8 bg-background shadow-[var(--clr-0)_0px_0px_10px_0px]">
                  <nav className="h-11 flex sticky top-0 justify-between" data-ditto-id="style-nav" data-component="nav">
                    <div className="flex items-center shrink-0">
                      <div className="block" data-ditto-id="style-div-8">
                        <img className="hidden max-w-full overflow-clip max-lg:w-6 max-lg:h-6 max-lg:inline-block" alt="Menu" role="button" src={iconFor("Menu")} />
                      </div>
                      <a className="block cursor-pointer aspect-[3.605] max-lg:aspect-[1.86]" data-ditto-id="style-pressed-juicery-home" data-component="link" aria-current="page" aria-label="Pressed Juicery Home" href="/">
                        <picture className="inline" data-ditto-id="motion-picture">
                          <source className="inline" data-ditto-id="style-source-2" media="(min-width: 1000px)" srcSet="/assets/cloned/images/pressed-wordmark.png" />
                          <img className="w-[9.6875rem] h-9.5 inline max-w-full px-4 overflow-clip max-lg:w-20" data-ditto-id="motion-image" data-component="image" src={iconFor("Pressed Juicery Home")} />
                        </picture>
                      </a>
                      <ul className="flex mx-4 gap-4 [list-style-type:none] max-lg:hidden" data-ditto-id="motion-ul">
                        <li className="list-item p-2">
                          <div className="block relative cursor-pointer">
                            <a className="inline" data-ditto-id="style-shop-dropdown" data-component="link" aria-expanded="false" aria-haspopup="menu" aria-label="Shop dropdown" href="/shop">
                              Shop
                            </a>
                          </div>
                        </li>
                        {ListRow_data.map((d, i) => <ListRow key={i} d={d} />)}
                      </ul>
                    </div>
                    <div className="flex items-center gap-4" data-ditto-id="style-div-9">
                      <div className="flex justify-end items-center cursor-pointer">
                        <div className="block" data-ditto-id="style-div-10">
                          <div className="block">
                            <div className="flex items-center" data-ditto-id="style-button" data-component="button" role="button">
                              <div className="h-4 flex mr-2 items-center">
                                <svg className="w-auto h-6 block overflow-hidden" data-ditto-id="style-icon" data-component="icon" aria-describedby="location_icon" aria-hidden="true" fill="none" height="24" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg">
                                  <title id="location_icon">
                                    {"Location Icon"}
                                  </title>
                                  <path d="M12 2C14.1217 2 16.1566 2.86721 17.6569 4.41084C19.1571 5.95448 20 8.0481 20 10.2311C20 13.7093 17.6246 17.4999 12.9354 21.6433C12.6746 21.8737 12.3422 22.0003 11.9985 22C11.6547 21.9997 11.3225 21.8725 11.0622 21.6416L10.752 21.3647C6.27036 17.3293 4 13.6316 4 10.2311C4 8.0481 4.84285 5.95448 6.34315 4.41084C7.84344 2.86721 9.87827 2 12 2ZM12 3.26633C10.2047 3.26633 8.48291 4.00012 7.21343 5.30627C5.94395 6.61243 5.23077 8.38395 5.23077 10.2311C5.23077 13.1876 7.32144 16.594 11.5602 20.4099L11.8663 20.6826C11.9035 20.7155 11.9509 20.7336 12 20.7336C12.0491 20.7336 12.0965 20.7155 12.1337 20.6826C16.5776 16.7553 18.7692 13.2577 18.7692 10.2311C18.7692 9.3165 18.5941 8.41083 18.254 7.56582C17.9138 6.72081 17.4152 5.95301 16.7866 5.30627C16.158 4.65953 15.4118 4.14651 14.5905 3.79649C13.7692 3.44648 12.8889 3.26633 12 3.26633ZM12 7.06531C12.8161 7.06531 13.5987 7.39885 14.1757 7.99256C14.7527 8.58626 15.0769 9.3915 15.0769 10.2311C15.0769 11.0708 14.7527 11.876 14.1757 12.4697C13.5987 13.0634 12.8161 13.397 12 13.397C11.1839 13.397 10.4013 13.0634 9.82429 12.4697C9.24725 11.876 8.92308 11.0708 8.92308 10.2311C8.92308 9.3915 9.24725 8.58626 9.82429 7.99256C10.4013 7.39885 11.1839 7.06531 12 7.06531ZM12 8.33164C11.5104 8.33164 11.0408 8.53176 10.6946 8.88799C10.3484 9.24421 10.1538 9.72735 10.1538 10.2311C10.1538 10.7349 10.3484 11.2181 10.6946 11.5743C11.0408 11.9305 11.5104 12.1306 12 12.1306C12.4896 12.1306 12.9592 11.9305 13.3054 11.5743C13.6516 11.2181 13.8462 10.7349 13.8462 10.2311C13.8462 9.72735 13.6516 9.24421 13.3054 8.88799C12.9592 8.53176 12.4896 8.33164 12 8.33164Z" fill="black" />
                                </svg>
                              </div>
                              <div className="block">
                                <div className="block mr-2 [font-family:regola-neue-semibold,_sans-serif] text-xs leading-[1rem]" data-ditto-id="style-div-11">
                                  Ship to
                                </div>
                                <div className="overflow-hidden text-xs leading-[1rem] underline line-clamp-1">
                                  {" Please enter an Address"}
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className="flex items-center shrink-0">
                        <div className="block relative">
                          <div className="flex items-center shrink-0 max-md:hidden" data-ditto-id="style-login" data-component="button" aria-label="login" role="button">
                            <img className="w-10 h-6 block max-w-full px-2 overflow-clip cursor-pointer" data-ditto-id="style-image-2" data-component="image" alt="My Account" src="/assets/cloned/svg/95449e8a8d0f.svg" />
                          </div>
                        </div>
                        <div className="flex relative bg-background" data-component="button" aria-label="Go to cart" role="button">
                          <img className="w-9.5 h-5 block max-w-full px-2 overflow-clip cursor-pointer" data-ditto-id="style-image" data-component="image" alt="" src={iconFor("Go to cart")} />
                        </div>
                      </div>
                    </div>
                  </nav>
                </div>
              </header>
              <main className="block" id="maincontent">
                <div className="block mx-auto">
                  <div className="block">
                    <div className="block max-w-360 mx-auto">
                      <div className="block relative -mb-1 aspect-[51/25] leading-0 bg-foreground bg-cover [background-position:50%_50%] bg-no-repeat" style={{ backgroundImage:"url(\"/assets/cloned/images/hero-poster.jpg\")" }}>
                        <video
                          className="w-full inline-block aspect-[51/25] object-fill"
                          data-ditto-id="style-div-12"
                          data-cloned-hero-video=""
                          autoPlay
                          loop
                          muted
                          playsInline
                          preload="auto"
                          poster="/assets/cloned/images/hero-poster.jpg"
                          src="/assets/cloned/video/hero-wicked-wonderland.mp4"
                        />
                        <div className="w-9 h-9 flex absolute top-6 left-305 rounded-full justify-center items-center max-md:left-[19.6875rem] md:max-lg:left-177" style={{ backgroundColor: "rgba(255,255,255,0.6)" }} data-ditto-id="style-heading-17" data-component="button" role="button">
                          <img className="w-5 h-5 block max-w-full overflow-clip" data-component="image" alt="Pause" src={iconFor("Pause")} />
                        </div>
                      </div>
                      <div className="block max-w-300 mx-auto py-16 px-6 text-center" data-ditto-id="style-span">
                        <div className="block">
                          <h1 className="block mb-6 text-5xl leading-14 max-md:[font-family:regola-neue-medium,_sans-serif]" data-ditto-id="style-font" data-component="heading">
                            Sip Into Wicked Wonderland
                          </h1>
                          <div className="block mb-6 text-2xl leading-8">
                            <p className="block mb-8 leading-[2.1875rem]">
                              Limited Edition Disney Descendants 6-pack
                            </p>
                          </div>
                          <a className="w-44 inline-block px-6 rounded-full text-background leading-12 bg-foreground cursor-pointer" data-ditto-id="style-div-34" data-component="button" href="https://pressed.com/products/disney-descendants-wicked-wonderland-bundle">
                            Shop the 6-Pack
                          </a>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="block" data-ditto-id="style-heading-28">
                    <div className="block max-w-256 mx-auto py-14 px-8 max-lg:py-8" data-ditto-id="style-br-23">
                      <div className="block" data-ditto-id="style-p-49">
                        <div className="block mb-8" data-ditto-id="style-p-25">
                          <h2 className="block mb-2 text-[2.5rem] font-bold leading-12 max-md:[font-family:regola-neue-medium,_sans-serif]" data-ditto-id="style-p-22" data-component="heading">
                            Everyday Wellness Favorites
                          </h2>
                          <p className="block mb-[1.33rem] leading-[1.4375rem]" data-ditto-id="style-strong-6">
                            {"Explore functional resets and nutrient-packed sips for your daily glow. "}
                            <strong className="inline font-bold" data-ditto-id="style-link-10">
                              Get $5 off pickup orders $50+.
                            </strong>
                          </p>
                        </div>
                        <div className="grid gap-4 grid-cols-3 max-lg:grid-cols-1" data-ditto-id="style-strong-7">
                          <div className="block mb-8" data-ditto-id="style-link-11">
                            <a className="inline cursor-pointer" data-ditto-id="style-strong-8" data-component="link" href="https://pressed.com/products/best-selling-juice-cleanse" rel="noopener noreferrer">
                              <img className="w-[19.3125rem] h-[19.3125rem] inline max-w-full overflow-clip max-md:w-[19.4375rem] max-md:h-[19.4375rem] md:max-lg:w-125 md:max-lg:h-125" data-ditto-id="style-link-12" data-component="image" src="/assets/cloned/images/c257619530f6.jpg" />
                            </a>
                            <a className="inline cursor-pointer" data-ditto-id="style-br-12" data-component="link" href="https://pressed.com/products/best-selling-juice-cleanse" rel="noopener noreferrer">
                              <h3 className="block mb-2 py-4 text-xl font-bold leading-7 max-md:[font-family:regola-neue-medium,_sans-serif]" data-ditto-id="style-link" data-component="heading">
                                Cleanse 2
                              </h3>
                            </a>
                            <p className="block mb-[1.33rem] leading-[1.4375rem]" data-ditto-id="style-div-91">
                              Reset with our most-loved cleanse.
                            </p>
                            <a className="inline font-bold underline cursor-pointer" data-ditto-id="style-figure-11" data-component="link" href="https://pressed.com/products/best-selling-juice-cleanse" rel="noopener noreferrer">
                              Order My Reset
                            </a>
                          </div>
                          <div className="block mb-8" data-ditto-id="style-div-92">
                            <a className="inline cursor-pointer" data-ditto-id="style-link-13" data-component="link" href="https://pressed.com/products/hydration-electrolyte-water-dragon-fruit" rel="noopener noreferrer">
                              <img className="w-[19.3125rem] h-[19.3125rem] inline max-w-full overflow-clip max-md:w-[19.4375rem] max-md:h-[19.4375rem] md:max-lg:w-176 md:max-lg:h-176" data-ditto-id="style-image-5" data-component="image" src="/assets/cloned/images/f84431265c1c.webp" />
                            </a>
                            <a className="inline cursor-pointer" data-ditto-id="style-div-77" data-component="link" href="https://pressed.com/products/hydration-electrolyte-water-dragon-fruit" rel="noopener noreferrer">
                              <h3 className="block mb-1 py-4 font-bold max-md:[font-family:regola-neue-medium,_sans-serif]" data-component="heading">
                                Hydration+ Watermelon Dragon Fruit
                              </h3>
                            </a>
                            <p className="block mb-[1.33rem] leading-[1.4375rem]" data-ditto-id="style-div-150">
                              Real-fruit hydration with 6 electrolytes.
                            </p>
                            <a className="inline font-bold underline cursor-pointer" data-ditto-id="style-div-78" data-component="link" href="https://pressed.com/products/hydration-electrolyte-water-dragon-fruit" rel="noopener noreferrer">
                              Shop Hydration
                            </a>
                          </div>
                          <div className="block mb-8" data-ditto-id="style-p-6">
                            <a className="inline cursor-pointer" data-ditto-id="style-div-28" data-component="link" href="https://pressed.com/products/best-selling-cold-pressed-juices-pack" rel="noopener noreferrer">
                              <img className="w-[19.3125rem] h-[19.3125rem] inline max-w-full overflow-clip max-md:w-[19.4375rem] max-md:h-[19.4375rem] md:max-lg:w-176 md:max-lg:h-176" data-ditto-id="style-hr-4" data-component="image" src="/assets/cloned/images/ecf63277d455.jpg" />
                            </a>
                            <a className="inline cursor-pointer" data-ditto-id="motion-div" data-component="link" href="https://pressed.com/products/best-selling-cold-pressed-juices-pack" rel="noopener noreferrer">
                              <h3 className="block mb-2 py-4 text-xl font-bold leading-7 max-md:[font-family:regola-neue-medium,_sans-serif]" data-ditto-id="style-p-14" data-component="heading">
                                Best-Selling Wellness Pack
                              </h3>
                            </a>
                            <p className="block mb-[1.33rem] leading-[1.4375rem]" data-ditto-id="style-div-93">
                              <span className="inline" data-ditto-id="style-div-21">
                                New to wellness? Start with bestsellers.
                              </span>
                            </p>
                            <a className="inline font-bold underline cursor-pointer" data-ditto-id="style-heading-19" data-component="link" href="https://pressed.com/products/best-selling-cold-pressed-juices-pack" rel="noopener noreferrer">
                              Sip On Bestsellers
                            </a>
                          </div>
                        </div>
                      </div>
                      <div className="block my-8" data-ditto-id="style-strong-37" id="frontpage-nosto-1">
                        <h2 className="block mb-6 text-[2rem] font-bold leading-10 max-md:[font-family:regola-neue-medium,_sans-serif]" data-ditto-id="style-br-55" data-component="heading">
                          Most Popular Right Now
                        </h2>
                        {""}
                        <ul className="grid gap-y-6 [list-style-type:none] grid-cols-5 max-md:grid-cols-2 md:max-lg:grid-cols-4" data-ditto-id="style-div-119">
                          {MediaCard_data.map((d, i) => <MediaCard key={i} d={d} styles={MediaCard_styles[i]} />)}
                        </ul>
                        {""}
                      </div>
                      <div className="border-t border-solid border-t-foreground block max-w-100 my-12 mx-auto max-md:max-w-none" data-ditto-id="style-p-21" />
                      <div className="flex mb-6 p-6 items-center gap-6 bg-color-006 max-lg:flex-col max-lg:gap-2 max-lg:text-center" data-ditto-id="style-br-57">
                        <img className="w-19.5 h-19.5 block max-w-20 mx-auto overflow-clip" data-ditto-id="style-br-18" data-component="image" src="/assets/cloned/svg/fbe8b2c3011a.svg" />
                        <div className="block" data-ditto-id="style-br-36">
                          <div className="block" data-ditto-id="style-div-99">
                            <h2 className="block mb-2 text-[2rem] font-bold leading-10 max-md:[font-family:regola-neue-medium,_sans-serif]" data-ditto-id="style-heading-6" data-component="heading">
                              Join Pressed Rewards
                            </h2>
                            <p className="block mb-[1.33rem] leading-[1.4375rem]">
                              Earn points. Get perks. Repeat. Wellness just got rewarding.
                            </p>
                          </div>
                        </div>
                        <a className="w-[9.2695rem] h-12 block pb-1 px-6 rounded-3xl shrink-0 overflow-hidden text-background [font-family:regola-neue-semibold,_sans-serif] leading-12 bg-foreground cursor-pointer" data-ditto-id="style-heading-18" data-component="link" href="/juice-subscription-membership/signup">
                          Join For Free
                        </a>
                      </div>
                      <div className="border-t border-solid border-t-foreground block max-w-100 my-12 mx-auto max-md:max-w-none" data-ditto-id="style-strong-4" />
                      <div className="block my-8" data-ditto-id="style-p-53" id="frontpage-nosto-2" />
                      <div className="block" data-ditto-id="style-br-10">
                        <div className="block mb-8" data-ditto-id="style-br-19">
                          <h2 className="block mb-2 text-[2.5rem] font-bold leading-12 max-md:[font-family:regola-neue-medium,_sans-serif]" data-ditto-id="style-br-11" data-component="heading">
                            Find Your Wellness Solution
                          </h2>
                          <p className="block mb-[1.33rem] leading-[1.4375rem]" data-ditto-id="style-div-100">
                            <span className="inline" data-ditto-id="style-div-17">
                              Discover the perfect solution for your needs with our essential wellness categories.
                            </span>
                          </p>
                        </div>
                        <div className="grid gap-4 grid-cols-4 max-lg:grid-cols-2" data-ditto-id="style-div-131">
                          {MediaTile_data.map((d, i) => <MediaTile key={i} d={d} />)}
                        </div>
                      </div>
                      <div className="border-t border-solid border-t-foreground block max-w-100 my-12 mx-auto max-md:max-w-none" data-ditto-id="style-heading-13" />
                      <div className="block" data-ditto-id="style-br-69">
                        <div className="block mb-8" data-ditto-id="style-br-75">
                          <h2 className="block mb-2 text-[2.5rem] font-bold leading-12 max-md:[font-family:regola-neue-medium,_sans-serif]" data-ditto-id="style-p-32" data-component="heading">
                            {"Cleanse & Detox"}
                          </h2>
                          <p className="block mb-[1.33rem] leading-[1.4375rem]" data-ditto-id="style-div-70">
                            Power your wellness with juice cleanses and solution packs designed to support your goals.
                          </p>
                        </div>
                        <div className="grid gap-4 grid-cols-2" data-ditto-id="style-div-59">
                          <div className="block mb-8">
                            <a className="inline cursor-pointer" data-ditto-id="style-div-35" data-component="link" href="/shop" rel="noopener noreferrer">
                              <img className="w-118 h-118 inline max-w-full overflow-clip max-md:w-37 max-md:h-37 md:max-lg:w-86 md:max-lg:h-86" data-ditto-id="style-hr-3" data-component="image" src="/assets/cloned/images/993905f7fe26.webp" />
                            </a>
                            <a className="inline cursor-pointer" data-ditto-id="style-div-60" data-component="link" href="/shop" rel="noopener noreferrer">
                              <h3 className="block mb-1 py-4 font-bold max-md:[font-family:regola-neue-medium,_sans-serif]" data-component="heading">
                                Juice Cleanses
                              </h3>
                            </a>
                            <p className="block mb-[1.33rem] leading-[1.4375rem]" data-ditto-id="style-div-61">
                              $35
                              <br className="inline" data-ditto-id="style-div-71" />
                              <span className="inline text-muted-foreground">
                                <strong className="inline font-bold" data-ditto-id="style-div-129">
                                  $30 VIP
                                </strong>
                              </span>
                            </p>
                            <a className="inline font-bold underline cursor-pointer" data-ditto-id="style-link-17" data-component="link" href="/shop" rel="noopener noreferrer">
                              Shop Cleanses
                            </a>
                          </div>
                          <div className="block mb-8" data-ditto-id="style-image-7">
                            <a className="inline cursor-pointer" data-ditto-id="style-heading-20" data-component="link" href="/shop" rel="noopener noreferrer">
                              <img className="w-118 h-118 inline max-w-full overflow-clip max-md:w-37 max-md:h-37 md:max-lg:w-86 md:max-lg:h-86" data-ditto-id="style-strong-18" data-component="image" src="/assets/cloned/images/a6729d2b25a9.jpg" />
                            </a>
                            <a className="inline cursor-pointer" data-ditto-id="style-p-39" data-component="link" href="/shop" rel="noopener noreferrer">
                              <h3 className="block mb-1 py-4 font-bold max-md:[font-family:regola-neue-medium,_sans-serif]" data-ditto-id="style-div-62" data-component="heading">
                                Juice and Shot Packs
                              </h3>
                            </a>
                            <p className="block mb-[1.33rem] leading-[1.4375rem]">
                              Starting at $22
                              <br className="inline" data-ditto-id="style-heading-14" />
                              <span className="inline text-muted-foreground" data-ditto-id="style-strong-22">
                                <strong className="inline font-bold" data-ditto-id="style-br-37">
                                  $20 VIP
                                </strong>
                              </span>
                            </p>
                            <a className="inline font-bold underline cursor-pointer" data-ditto-id="style-p-40" data-component="link" href="/shop" rel="noopener noreferrer">
                              Shop Juice Packs
                            </a>
                          </div>
                        </div>
                      </div>
                      <div className="border-t border-solid border-t-foreground block max-w-100 my-12 mx-auto max-md:max-w-none" data-ditto-id="style-div-63" />
                      <div className="block" data-ditto-id="style-heading-27">
                        <div className="block mb-8" data-ditto-id="style-strong-19">
                          <h2 className="block mb-2 text-[2.5rem] font-bold leading-12 max-md:[font-family:regola-neue-medium,_sans-serif]" data-ditto-id="style-br-73" data-component="heading">
                            View Our Menu
                          </h2>
                          <p className="block mb-[1.33rem] leading-[1.4375rem]" data-ditto-id="style-p-54">
                            Explore 100% cold-pressed juices, protein smoothies, acai bowls, and more.
                          </p>
                        </div>
                        <div className="grid gap-4 grid-cols-3 grid-rows-[498.016px_498.016px] max-lg:grid-cols-2 max-md:grid-rows-[calc(27.143vw_+_282.386px)_calc(50vw_+_172.672px)_calc(27.143vw_+_282.386px)] md:max-lg:grid-rows-[calc(50vw_+_148.672px)_calc(50vw_+_148.672px)_calc(50vw_+_148.672px)]" data-ditto-id="style-div-132">
                          {MediaCard2_data.map((d, i) => <MediaCard2 key={i} d={d} />)}
                        </div>
                      </div>
                      <div className="block my-8" data-ditto-id="style-br-66" id="homepage-nosto-1" />
                      <div className="border-t border-solid border-t-foreground block max-w-100 my-12 mx-auto max-md:max-w-none" data-ditto-id="style-br-49" />
                      <div className="flex mb-6 p-6 items-center gap-6 bg-color-006 max-lg:flex-col max-lg:gap-2 max-lg:text-center" data-ditto-id="style-strong-21">
                        <img className="w-19.5 h-19.5 block max-w-20 overflow-clip mx-auto" data-ditto-id="style-br-58" data-component="image" src="/assets/cloned/svg/df485cd6f139.svg" />
                        <div className="block" data-ditto-id="style-br-67">
                          <div className="block" data-ditto-id="style-link-21">
                            <h2 className="block mb-2 text-[2rem] font-bold leading-10 max-md:[font-family:regola-neue-medium,_sans-serif]" data-ditto-id="style-u-3" data-component="heading">
                              Pressed Catering
                            </h2>
                            <p className="block mb-[1.33rem] leading-[1.4375rem]">
                              {"From "}
                              <strong className="inline font-bold" data-ditto-id="style-br-39">
                                weddings
                              </strong>
                              {" and "}
                              <strong className="inline font-bold">
                                wellness retreats
                              </strong>
                              {" to "}
                              <strong className="inline font-bold" data-ditto-id="style-br-50">
                                corporate gatherings
                              </strong>
                              {" and "}
                              <strong className="inline font-bold" data-ditto-id="style-br-40">
                                parties
                              </strong>
                              {", our wellness catering brings the vibes (and vitamins)."}
                            </p>
                          </div>
                        </div>
                        <a className="w-[168.25px] h-12 block pb-1 px-6 rounded-3xl shrink-0 overflow-hidden text-background [font-family:regola-neue-semibold,_sans-serif] leading-12 bg-foreground cursor-pointer" data-ditto-id="style-link-22" data-component="link" href="/catering">
                          Order Catering
                        </a>
                      </div>
                      <div className="block my-8" id="homepage-nosto-2" />
                      <div className="border-t border-solid border-t-foreground block max-w-100 my-12 mx-auto max-md:max-w-none" data-ditto-id="style-div-68" />
                      <div className="block" data-ditto-id="style-div-135">
                        <div className="block mb-8">
                          <h2 className="block mb-2 text-[2.5rem] font-bold leading-12 max-md:[font-family:regola-neue-medium,_sans-serif]" data-ditto-id="style-div-36" data-component="heading">
                            Wellness, Your Way
                          </h2>
                          <p className="block mb-[1.33rem] leading-[1.4375rem]" data-ditto-id="style-p-28">
                            From in-store to your front door, get your wellness favorites your way.
                          </p>
                        </div>
                        <div className="grid gap-4 grid-cols-4 max-lg:grid-cols-2" data-ditto-id="style-div-136">
                          <div className="block py-6 px-12 rounded-[20px] text-center bg-color-006 max-lg:p-4" data-ditto-id="style-hr-5">
                            <img className="w-19.5 h-19.5 inline max-w-20 overflow-clip max-lg:w-16 max-lg:h-16 max-lg:max-w-16" data-ditto-id="style-div-144" data-component="image" src="/assets/cloned/svg/ec054ab5c3ba.svg" />
                            <h3 className="block mb-1 font-bold max-md:[font-family:regola-neue-medium,_sans-serif]" data-component="heading">
                              Shop In-Store
                            </h3>
                            <p className="block mb-[1.33rem] leading-[1.4375rem]" data-ditto-id="style-div-133">
                              Visit us + explore our selection at your local Pressed Juicery.
                            </p>
                          </div>
                          <div className="block py-6 px-12 rounded-[20px] text-center bg-color-006 max-lg:p-4">
                            <img className="w-19.5 h-19.5 inline max-w-20 overflow-clip max-lg:w-16 max-lg:h-16 max-lg:max-w-16" data-component="image" src="/assets/cloned/svg/e23a7fafb92c.svg" />
                            <h3 className="block mb-1 font-bold max-md:[font-family:regola-neue-medium,_sans-serif]" data-ditto-id="style-strong-49" data-component="heading">
                              In-Store Pickup
                            </h3>
                            <p className="block mb-[1.33rem] leading-[1.4375rem]" data-ditto-id="style-strong-10">
                              Shop online and pick up your order at a local store near you.
                            </p>
                          </div>
                          <div className="block py-6 px-12 rounded-[20px] text-center bg-color-006 max-lg:p-4" data-ditto-id="style-div-145">
                            <img className="w-19.5 h-19.5 inline max-w-20 overflow-clip max-lg:w-16 max-lg:h-16 max-lg:max-w-16" data-component="image" src="/assets/cloned/svg/7262438c3e1c.svg" />
                            <h3 className="block mb-1 font-bold max-md:[font-family:regola-neue-medium,_sans-serif]" data-ditto-id="style-div-146" data-component="heading">
                              Local Delivery
                            </h3>
                            <p className="block mb-[1.33rem] leading-[1.4375rem]" data-ditto-id="style-p">
                              <span className="inline text-clr-1" data-ditto-id="style-strong-36">
                                Enjoy delivery to your door if you’re near a Pressed store.
                              </span>
                            </p>
                          </div>
                          <div className="block py-6 px-12 rounded-[20px] text-center bg-color-006 max-lg:p-4" data-ditto-id="style-ul">
                            <img className="w-19.5 h-19.5 inline max-w-20 overflow-clip max-lg:w-16 max-lg:h-16 max-lg:max-w-16" data-ditto-id="style-heading-25" data-component="image" src="/assets/cloned/svg/91f513a23bb7.svg" />
                            <h3 className="block mb-1 font-bold max-md:[font-family:regola-neue-medium,_sans-serif]" data-ditto-id="style-p-2" data-component="heading">
                              Ship It To Me
                            </h3>
                            <p className="block mb-[1.33rem] leading-[1.4375rem]" data-ditto-id="style-br-71">
                              Experience fast shipping, from our warehouse to your door.
                            </p>
                          </div>
                        </div>
                      </div>
                      <div className="border-t border-solid border-t-foreground block max-w-100 my-12 mx-auto max-md:max-w-none" data-ditto-id="style-p-3" />
                      <div className="block text-center" data-ditto-id="style-div-130">
                        <div className="block max-w-175 mx-auto" data-ditto-id="style-div">
                          <h2 className="block mb-2 text-2xl font-bold leading-8 max-md:[font-family:regola-neue-medium,_sans-serif]" data-component="heading">
                            Our Product Philosophy
                          </h2>
                          <p className="block mb-[1.33rem] leading-[1.4375rem]" data-ditto-id="style-ul-2">
                            <span className="inline" data-ditto-id="style-div-137">
                              We're committed to elevating your wellness journey with premium ingredients, vibrant flavors, and expertly sourced products.
                            </span>
                          </p>
                        </div>
                        <a className="w-[8.6445rem] h-12 inline-block mb-6 pb-1 px-6 rounded-3xl overflow-hidden text-background [font-family:regola-neue-semibold,_sans-serif] leading-12 bg-foreground cursor-pointer" data-ditto-id="style-link-6" data-component="button" href="/our-journey" rel="noopener noreferrer">
                          Learn More
                        </a>
                        <img className="w-240 h-[23.6875rem] inline max-w-full overflow-clip max-md:w-[19.4375rem] max-md:h-[7.6875rem] md:max-lg:w-176 md:max-lg:h-69.5" data-ditto-id="style-image-14" data-component="image" src="/assets/cloned/images/3c147e466779.webp" />
                      </div>
                    </div>
                  </div>
                </div>
              </main>
            </div>
            <footer className="block py-20 text-background bg-foreground max-lg:pt-10 max-lg:pb-16" data-ditto-id="style-heading">
              <div className="h-full block" data-ditto-id="style-div-152">
                <div className="h-full block max-w-360 mx-auto px-16 max-md:px-6 md:max-lg:px-8" data-ditto-id="style-figure">
                  <div className="border-b border-solid border-b-background grid mb-6 pb-10 gap-x-[5%] grid-cols-[40px_162px_minmax(0,1fr)] max-lg:block max-lg:grid-cols-[40px_162px_auto] max-lg:border-b-[0] max-lg:border-initial max-lg:border-b-[initial] max-lg:pb-0" data-ditto-id="style-div-138">
                    <a className="h-11 block mb-10 cursor-pointer max-lg:inline-block" data-ditto-id="style-link-7" data-component="link" aria-current="page" href="/">
                      <img className="w-10 h-10 inline max-w-full overflow-clip" data-ditto-id="style-image-8" data-component="image" alt="Pressed Juicery logo" src={iconFor("Pressed Juicery logo")} />
                    </a>
                    <div className="block" data-ditto-id="style-div-2">
                      <form className="block mb-6">
                        <div className="w-full block md:max-lg:w-[61%]" data-ditto-id="style-p-4">
                          <h2 className="block mb-3 [font-family:regola-neue-semibold,_sans-serif] leading-[1.1875rem]" data-component="heading">
                            Sign up for our newsletter
                          </h2>
                          <div className="block mb-3 text-sm leading-4" data-ditto-id="style-p-5">
                            Get the latest news and offers by signing up for our newsletter!
                          </div>
                          <div className="block mb-3" data-ditto-id="style-div-75" aria-label="Enter your email to sign up for our newsletter">
                            <div className="block mb-1 leading-3.5" data-ditto-id="style-hr" id="lbl_v-0-0">
                              <label className="inline [font-family:regola-neue-semibold,_sans-serif] leading-6 cursor-default" htmlFor="v-0-0">
                                Enter your email
                              </label>
                            </div>
                            <input className="w-full h-10.5 border-2 border-solid border-background block mb-3 py-2 px-4 rounded-[10px] overflow-clip leading-4 tracking-[normal] cursor-text" data-ditto-id="style-code" data-component="input" aria-describedby="error_v-0-0" aria-label="Enter your email to sign up for our newsletter" id="v-0-0" />
                          </div>
                          <button className="h-10 border-2 border-solid border-background flex pt-2 pb-3 px-4 rounded-full justify-center items-center leading-[1.125rem] tracking-[normal] text-center whitespace-nowrap bg-foreground cursor-pointer" data-ditto-id="style-figure-10" data-component="button" aria-label="Submit entered email to sign up for our newsletter" role="button" type="submit">
                            {" Sign Up"}
                          </button>
                        </div>
                      </form>
                      <div className="block max-lg:hidden">
                        <h2 className="block pb-2 [font-family:regola-neue-semibold,_sans-serif]" data-ditto-id="style-div-76" data-component="heading">
                          Get the App
                        </h2>
                        <ul className="grid grid-cols-[162px] [list-style-type:none]" data-ditto-id="style-div-147">
                          <li className="list-item pb-2" data-ditto-id="style-p-55">
                            <a className="inline cursor-pointer" data-ditto-id="style-div-37" data-component="link" href="https://apps.apple.com/us/app/pressed-juicery/id1529648960" rel="noopener" target="_blank">
                              <img className="w-36 h-12 inline max-w-full overflow-clip" data-ditto-id="style-hr-6" data-component="image" alt="download from the App Store" src="/assets/cloned/svg/9bccd60d7d6e.svg" />
                            </a>
                          </li>
                          <li className="list-item" data-ditto-id="style-div-148">
                            <a className="inline cursor-pointer" data-ditto-id="style-p-42" data-component="link" href="https://play.google.com/store/apps/details?id=com.pressedjuicery.app" rel="noopener" target="_blank">
                              <img className="w-40.5 h-12 inline max-w-full overflow-clip" data-component="image" alt="download from Google Play" src="/assets/cloned/svg/fbffbc22336d.svg" />
                            </a>
                          </li>
                        </ul>
                      </div>
                    </div>
                    <div className="grid gap-x-[5%] grid-cols-[3224fr_1184fr_1475fr_1097fr_3100fr] max-lg:block max-lg:mb-6 max-lg:grid-cols-[auto_auto_auto_auto_auto]" data-ditto-id="style-div-149">
                      <div className="block max-lg:border-b max-lg:border-solid max-lg:border-b-background max-lg:mb-6 max-lg:pb-6">
                        <h2 className="block pb-2 [font-family:regola-neue-semibold,_sans-serif]" data-component="heading">
                          Membership
                        </h2>
                        <div className="block pb-4" data-ditto-id="style-div-139">
                          {" Enjoy VIP pricing and earn treats when you subscribe to a Pressed Juicery® Membership."}
                        </div>
                        <a className="inline rounded-xs underline cursor-pointer" data-ditto-id="style-div-83" data-component="link" href="/juice-subscription-membership/signup">
                          {" Sign Up"}
                        </a>
                      </div>
                      <div className="block max-lg:border-b max-lg:border-solid max-lg:border-b-background max-lg:mb-6 max-lg:pb-6" data-ditto-id="style-div-102">
                        <h2 className="block pb-2 [font-family:regola-neue-semibold,_sans-serif]" data-ditto-id="style-p-59" data-component="heading">
                          Shop
                        </h2>
                        <ul className="flex flex-col [list-style-type:none] max-lg:flex-wrap max-lg:gap-[4%] max-lg:[flex-direction:initial]" data-ditto-id="style-heading-29">
                          {ListRow2_data.map((d, i) => <ListRow2 key={i} d={d} styles={ListRow2_styles[i]} />)}
                        </ul>
                      </div>
                      <div className="block max-lg:border-b max-lg:border-solid max-lg:border-b-background max-lg:mb-6 max-lg:pb-6">
                        <h2 className="block pb-2 [font-family:regola-neue-semibold,_sans-serif]" data-component="heading">
                          Learn
                        </h2>
                        <ul className="flex flex-col [list-style-type:none] max-lg:flex-wrap max-lg:gap-[4%] max-lg:[flex-direction:initial]" data-ditto-id="style-h1-2">
                          {ListRow3_data.map((d, i) => <ListRow3 key={i} d={d} styles={ListRow3_styles[i]} />)}
                        </ul>
                      </div>
                      <div className="block max-lg:border-b max-lg:border-solid max-lg:border-b-background max-lg:mb-6 max-lg:pb-6" data-ditto-id="style-p-57">
                        <h2 className="block pb-2 [font-family:regola-neue-semibold,_sans-serif]" data-component="heading">
                          Support
                        </h2>
                        <ul className="flex flex-col [list-style-type:none] max-lg:flex-wrap max-lg:gap-[4%] max-lg:[flex-direction:initial]" data-ditto-id="style-strong-46">
                          {ListRow4_data.map((d, i) => <ListRow4 key={i} d={d} styles={ListRow4_styles[i]} />)}
                        </ul>
                      </div>
                      <div className="block max-lg:border-b max-lg:border-solid max-lg:border-b-background max-lg:mb-6 max-lg:pb-6" data-ditto-id="style-div-40">
                        <h2 className="block pb-2 [font-family:regola-neue-semibold,_sans-serif]" data-component="heading">
                          Policies
                        </h2>
                        <ul className="flex flex-col [list-style-type:none] max-lg:flex-wrap max-lg:gap-[4%] max-lg:[flex-direction:initial]" data-ditto-id="style-p-62">
                          {ListRow5_data.map((d, i) => <ListRow5 key={i} d={d} styles={ListRow5_styles[i]} />)}
                        </ul>
                      </div>
                    </div>
                    <div className="hidden min-w-0 max-lg:block max-lg:mb-6 max-lg:justify-between max-lg:items-end" data-ditto-id="style-figure-16">
                      <div className="block">
                        <h2 className="block pb-2 [font-family:regola-neue-semibold,_sans-serif]">
                          Get the App
                        </h2>
                        <ul className="grid grid-cols-[auto] [list-style-type:none] max-lg:flex max-lg:mb-10 max-lg:items-start" data-ditto-id="style-h3-9">
                          <li className="list-item min-w-0 pb-2" data-ditto-id="style-strong-51">
                            <a className="inline cursor-pointer max-lg:mr-6" href="https://apps.apple.com/us/app/pressed-juicery/id1529648960" rel="noopener" target="_blank">
                              <img className="inline max-w-full overflow-clip max-lg:w-36 max-lg:h-12" alt="download from the App Store" src="/assets/cloned/svg/9bccd60d7d6e.svg" />
                            </a>
                          </li>
                          <li className="list-item min-w-0">
                            <a className="inline cursor-pointer max-lg:mr-6" href="https://play.google.com/store/apps/details?id=com.pressedjuicery.app" rel="noopener" target="_blank">
                              <img className="inline max-w-full overflow-clip max-lg:w-40.5 max-lg:h-12" alt="download from Google Play" src="/assets/cloned/svg/fbffbc22336d.svg" />
                            </a>
                          </li>
                        </ul>
                      </div>
                      <ul className="hidden [list-style-type:none] max-lg:flex" data-ditto-id="style-div-154">
                        {Logo2_data.map((d, i) => <Logo2 key={i} d={d} styles={Logo2_styles[i]} />)}
                      </ul>
                    </div>
                  </div>
                  <div className="flex justify-between max-lg:mb-1">
                    <div className="flex max-lg:flex-col" data-ditto-id="style-div-140">
                      <div className="block mr-6 max-lg:mb-2" data-ditto-id="style-p-63">
                        Ⓒ 2026 Pressed Juicery®
                      </div>
                      <ul className="flex [list-style-type:none] max-lg:flex-col">
                        {ListRow6_data.map((d, i) => <ListRow6 key={i} d={d} styles={ListRow6_styles[i]} />)}
                      </ul>
                    </div>
                    <ul className="flex [list-style-type:none] max-lg:hidden">
                      {Logo3_data.map((d, i) => <Logo3 key={i} d={d} styles={Logo3_styles[i]} />)}
                    </ul>
                  </div>
                  <div className="block" data-ditto-id="style-strong-52">
                    <a className="inline mr-6 cursor-pointer" data-ditto-id="style-br-54" data-component="link" href="https://pressed.com/legal/sensitive-personal-information-statement">
                      {" Limit the Use of My Sensitive Personal Information"}
                    </a>
                  </div>
                </div>
              </div>
            </footer>
          </div>
        </div>
      </div>
      <div className="block" id="teleports" />
      <div className="block" />
      <iframe className="w-px h-px block absolute -top-[624.9375rem] overflow-clip" aria-hidden="true" role="presentation" title="Blank" />
      <div className="w-[34.1094px] h-5.5 block absolute -top-[6249.9375rem] -left-[6249.9375rem] leading-5.5 whitespace-nowrap">
        Mgy
      </div>
    </>
  );
}
