import { iconFor } from "../_icons";
import"./ditto.css";
import DittoMotion from"../ditto/DittoMotion";
import DropdownMenu from"../ditto/DropdownMenu";
import Logo from"./components/logo";
import ListRow from"./components/list-row";
import ListRow2 from"./components/list-row2";
import ListRow3 from"./components/list-row3";
import ListRow4 from"./components/list-row4";
import Logo2 from"./components/logo2";
import ListRow5 from"./components/list-row5";
import Logo3 from"./components/logo3";
// Generated by clone-site. Do not edit by hand.
const Logo_data = [
    { ariaLabel:"View previous offer" },
    { ariaLabel:"View next offer" },
    { ariaLabel:"Pause offer carousel" }
];
const ListRow_data = [
    { href:"/our-journey", label:"About" },
    { href:"/juice-subscription-membership/signup", label:"Pressed Rewards" },
    { href:"/juice-bar-locations", label:"Find a Store" },
    { href:"/flavor-quiz", ariacurrent:"page", label:"Quiz" },
    { href:"/catering", label:"Catering" }
];
const ListRow2_data = [
    { href:"/shop", label:"Shop All" },
    { href:"/juice-bar-locations", label:"Find a Store" },
    { href:"https://pressed.com/foodservice", label:"Wholesale" },
    { href:"/catering", label:"Catering" }
];
const ListRow3_data = [
    { href:"/our-journey", label:"Our Story" },
    { href:"https://pressed.com/blogs/pressed-life", label:"Blog" },
    { href:"https://pressed.com/juice-cleanses", label:"Juice Cleanses" },
    { href:"https://pressed.com/acai-bowls", label:"Acai Bowls" },
    { href:"https://pressed.com/cleanse-guide", label:"Cleanse Guide" },
    { href:"/juice-subscription-membership/signup", label:"Rewards" },
    { href:"https://pressed.com/gut-biome-sulforaphane-benefits", label:"Gut Biome+" }
];
const ListRow2_data2 = [
    { href:"https://pressed.com/pages/contact-us", label:"Contact Us" },
    { href:"https://pressed.com/faqs", label:"FAQs" },
    { href:"https://pressed.com/allergens", label:"Nutrition" },
    { href:"https://pressed.com/careers", label:"Careers" }
];
const ListRow4_data = [
    { href:"https://pressed.com/legal/shipping-policy", label:"Shipping & Delivery" },
    { href:"https://pressed.com/legal/refund-and-cancellation-policy", label:"Refund & Cancellation" },
    { href:"https://pressed.com/legal/member-terms-and-conditions", label:"Member Terms and Conditions" },
    { href:"https://pressed.com/legal/vip-terms-and-conditions", label:"VIP Terms and Conditions" },
    { href:"https://pressed.com/legal/accessibility-policy", label:"Accessibility Policy" }
];
const Logo2_data = [
    { href:"https://www.instagram.com/pressedjuicery/", alt:"Instagram" },
    { href:"https://www.facebook.com/PressedOfficial", alt:"Facebook" },
    { href:"https://x.com/pressedjuicery", alt:"Twitter" },
    { href:"https://www.youtube.com/channel/UC5E5Wd9hZaZoyJU25cKeRsg", alt:"YouTube" }
];
const ListRow5_data = [
    { href:"https://pressed.com/legal/terms-of-use", label:"Terms of Use" },
    { href:"https://pressed.com/legal/privacy-policy", label:"Privacy Policy" },
    { href:"javascript:Cookiebot.show()", label:"Do Not Sell or Share My Personal Information" }
];
const Logo3_data = [
    { href:"https://www.instagram.com/pressedjuicery/", alt:"Instagram" },
    { href:"https://www.facebook.com/PressedOfficial", alt:"Facebook" },
    { href:"https://x.com/pressedjuicery", alt:"Twitter" },
    { href:"https://www.youtube.com/channel/UC5E5Wd9hZaZoyJU25cKeRsg", alt:"YouTube" }
];
const Logo_meta: string[][] = [
    ["style-div-8","n24"],
    ["style-pressed-juicery-home","motion-picture"],
    ["style-source-2","motion-image"]
];
const ListRow_meta: string[][] = [
    ["style-33","style-div-9"],
    ["n44","style-div-10"],
    ["n46","style-button"],
    ["n48","style-icon"],
    ["n50","style-div-11"]
];
const ListRow2_meta: string[][] = [
    ["motion-div-2","style-div-79"],
    ["style-image-15","style-div-114"],
    ["n111","style-div-94"],
    ["style-h1","style-strong-38"]
];
const ListRow3_meta: string[][] = [
    ["n118","style-div-116"],
    ["style-div-96","style-a-5"],
    ["style-u","style-br-65"],
    ["n124","style-strong-39"],
    ["n126","style-p-46"],
    ["style-a","style-p-50"],
    ["n130","style-h3-6"]
];
const ListRow2_meta2: string[][] = [
    ["style-figure-13","style-div-117"],
    ["style-image-10","style-heading-3"],
    ["style-strong-2","style-p-7"],
    ["style-div-31","style-p-51"]
];
const ListRow4_meta: string[][] = [
    ["style-heading-22","style-strong-3"],
    ["style-p-60","style-div-118"],
    ["style-p-8","style-figure-2"],
    ["style-div-32","style-image-4"],
    ["style-heading-7","style-strong-40"]
];
const Logo2_meta: string[][] = [
    ["style-heading-8","style-div-98","style-div-24"],
    ["style-heading-2","style-br-13","style-br"],
    ["style-figure-4","style-div-15","style-link-14"],
    ["style-image-3","style-p-17","style-strong-33"]
];
const ListRow5_meta: string[][] = [
    ["style-br-3","style-link-3"],
    ["style-br-4","style-p-19"],
    ["style-div-16","style-heading-4"]
];
const Logo3_meta: string[][] = [
    ["style-br-14","style-figure-3","style-div-25"],
    ["style-link-15","style-image-6","style-p-23"],
    ["style-strong-34","style-p-20","style-br-6"],
    ["style-br-15","style-br-7","style-br-16"]
];
const Logo_styles = [
    { className:"w-2 h-3" },
    { className:"w-2 h-3" },
    { className:"w-3.5 h-4" }
];
const ListRow2_styles = [
    { className:"w-[92.7031px] pb-2 max-md:w-[150.406px] md:max-lg:w-[323.828px]" },
    { className:"w-[92.7px] pb-2 max-md:w-[calc(46.01vw_-_22.126px)] md:max-lg:w-[calc(46vw_-_29.45px)]" },
    { className:"w-[92.7031px] pb-2 max-md:w-[150.406px] md:max-lg:w-[323.828px]" },
    { className:"w-[92.7031px] max-md:w-[150.406px] md:max-lg:w-[323.828px]" }
];
const ListRow3_styles = [
    { className:"pb-2 max-md:w-[150.406px] md:max-lg:w-[323.828px]" },
    { className:"pb-2 max-md:w-[150.406px] md:max-lg:w-[323.828px]" },
    { className:"pb-2 max-md:w-[calc(46.01vw_-_22.126px)] md:max-lg:w-[calc(46vw_-_29.45px)]" },
    { className:"pb-2 max-md:w-[150.406px] md:max-lg:w-[323.828px]" },
    { className:"pb-2 max-md:w-[calc(46.01vw_-_22.126px)] md:max-lg:w-[calc(46vw_-_29.45px)]" },
    { className:"pb-2 max-md:w-[150.406px] md:max-lg:w-[323.828px]" },
    { className:"max-md:w-[150.406px] md:max-lg:w-[323.828px]" }
];
const ListRow2_styles2 = [
    { className:"w-[5.37rem] pb-2 max-md:w-[calc(46.01vw_-_22.126px)] md:max-lg:w-[calc(46vw_-_29.45px)]" },
    { className:"w-[85.9219px] pb-2 max-md:w-[150.406px] md:max-lg:w-[323.828px]" },
    { className:"w-[85.9219px] pb-2 max-md:w-[150.406px] md:max-lg:w-[323.828px]" },
    { className:"w-[85.9219px] max-md:w-[150.406px] md:max-lg:w-[323.828px]" }
];
const ListRow4_styles = [
    { className:"pb-2" },
    { className:"pb-2" },
    { className:"pb-2" },
    { className:"pb-2" },
    {  }
];
const Logo2_styles = [
    { className:"mr-4", className2:"max-lg:w-6 max-lg:h-6" },
    { className:"mr-4", className2:"max-lg:w-3 max-lg:h-6" },
    { className:"mr-4", className2:"max-lg:w-6 max-lg:h-5" },
    { className2:"max-lg:w-6 max-lg:h-4" }
];
const ListRow5_styles = [
    { className:"mr-6" },
    { className:"mr-6" },
    {  }
];
const Logo3_styles = [
    { className:"mr-4", className2:"w-6 h-6" },
    { className:"mr-4", className2:"w-3 h-6" },
    { className:"mr-4", className2:"w-6 h-5" },
    { className2:"w-6 h-4" }
];

export default function Page() {
  return (
    <>
      <div className="h-[488.5px] block fixed right-214 bottom-6 left-6 z-99999999 max-w-100 p-6 rounded-[10px] text-background text-[0.9375rem] leading-[1.4375rem] bg-color-003 max-md:h-[31.9375rem] max-md:bottom-0 max-md:inset-x-0 max-md:max-w-none max-md:rounded-br-[initial] max-md:rounded-bl-[initial] md:max-lg:right-86" id="cookie-banner" name="cookie-banner">
        <div className="block mb-2 [font-family:regola-neue-semibold,_sans-serif] text-xl leading-7.5">
          This website uses cookies and other tracking technology
        </div>
        <div className="block mb-6">
          {"We use cookies and other tracking technology to personalize content and ads, provide social media features and to analyze our traffic. We also share information about you and your use of our site with our social media, advertising and analytics partners who may combine this information with other information that you have provided to them or that they have collected from your use of their services, as detailed in our"}
          <a className="inline underline cursor-pointer" data-ditto-id="style-default-layout-header-wrapper" data-component="link" href="https://pressed.com/legal/privacy-policy">
            Privacy Policy
          </a>
          . By continuing to our website, you consent to our uses of cookies and other tracking technologies.
        </div>
        <div className="block">
          <a className="h-10 flex mb-4 px-4 rounded-sm justify-center items-center text-color-003 [font-family:regola-neue-semibold,_sans-serif] leading-[0.9375rem] text-center uppercase bg-background cursor-pointer" data-ditto-id="style-pressed-header" data-component="button" href="javascript:void(0)" role="button">
            <span className="block">
              Continue to site
            </span>
          </a>
          <a className="block text-center underline cursor-pointer" data-ditto-id="style-div-6" data-component="button" href="javascript:void(0)" role="button">
            <span className="inline">
              Do Not Sell or Share My Personal Information
            </span>
          </a>
        </div>
      </div>
      <div className="block" id="__nuxt">
        <div className="block">
          <div className="min-h-screen grid grid-cols-1" data-ditto-id="style-viewallofferselement">
            <div className="block" data-ditto-id="style-div-7" id="default-layout-header-wrapper">
              <a className="w-[244.828px] h-11.5 border-r border-solid border-r-color-002 border-b border-b-color-002 block absolute -top-12 z-101 pt-1.5 pb-0.5 px-1.5 overflow-hidden text-2xl leading-9 bg-background cursor-pointer" data-ditto-id="style-link-9" data-component="link" href="#maincontent">
                Skip to main content
              </a>
              <header className="h-[8.6875rem] block sticky top-0 z-100 max-md:h-[9.4375rem] md:max-lg:h-[8.1875rem]" id="pressed-header">
                <div className="min-h-10 block py-3 text-background [font-family:regola-neue-medium,_sans-serif] bg-foreground max-md:h-15 max-md:flex max-md:py-1 max-md:items-center" data-ditto-id="style-div-3">
                  <div className="block max-w-360 px-16 mx-auto max-md:px-6 md:max-lg:px-8">
                    <div className="flex justify-between items-center" data-ditto-id="style-div-4">
                      <div className="flex px-4 flex-wrap justify-center grow gap-1 text-center max-md:flex-col max-lg:items-center max-lg:[font-family:regola-neue-semibold,_sans-serif] max-lg:text-xs max-lg:leading-[1rem] max-md:gap-[initial]" aria-label="View all offers Carousel" aria-live="polite" role="region">
                        <span className="overflow-hidden line-clamp-1 max-md:line-clamp-3">
                          $5 Off on Pickup Orders of $50 or More
                        </span>
                        <span className="block ml-4 underline whitespace-nowrap cursor-pointer max-lg:ml-0" data-ditto-id="style-nav" data-component="button" id="viewAllOffersElement" role="button">
                          {" View All Offers"}
                        </span>
                      </div>
                      <div className="flex shrink-0">
                        {Logo_data.map((d, i) => <Logo key={i} d={d} styles={Logo_styles[i]} />)}
                      </div>
                    </div>
                  </div>
                </div>
                <div className="block py-6 px-8 bg-background shadow-[var(--clr-0)_0px_0px_10px_0px]" data-ditto-id="motion-ul">
                  <nav className="h-11 flex sticky top-0 justify-between" data-component="nav">
                    <div className="flex items-center shrink-0">
                      <div className="block" data-ditto-id="style-shop-dropdown">
                        <img className="hidden max-w-full overflow-clip max-lg:w-6 max-lg:h-6 max-lg:inline-block" alt="Menu" role="button" src={iconFor("Menu")} />
                      </div>
                      <a className="block cursor-pointer aspect-[3.605] max-lg:aspect-[1.86]" data-ditto-id="style-pressed-juicery-home-2" data-component="link" aria-label="Pressed Juicery Home" href="/">
                        <picture className="inline">
                          <source className="inline" data-ditto-id="style-source" media="(min-width: 1000px)" srcSet="/assets/cloned/images/pressed-wordmark.png" />
                          <img className="w-[9.6875rem] h-9.5 inline max-w-full px-4 overflow-clip max-lg:w-20" data-component="image" src={iconFor("Pressed Juicery Home")} />
                        </picture>
                      </a>
                      <ul className="flex mx-4 gap-4 [list-style-type:none] max-lg:hidden" data-ditto-id="style-ul-3">
                        <li className="list-item p-2">
                          <div className="block relative cursor-pointer" data-ditto-id="style-div-5">
                            <a className="inline" data-ditto-id="style-shop-dropdown-2" data-component="link" aria-expanded="false" aria-haspopup="menu" aria-label="Shop dropdown" href="/shop">
                              Shop
                            </a>
                          </div>
                        </li>
                        {ListRow_data.map((d, i) => <ListRow key={i} d={d} />)}
                      </ul>
                    </div>
                    <div className="flex items-center gap-4">
                      <div className="flex justify-end items-center cursor-pointer">
                        <div className="block">
                          <div className="block" data-ditto-id="style-login">
                            <div className="flex items-center" data-ditto-id="style-image-2" data-component="button" role="button">
                              <div className="h-4 flex mr-2 items-center">
                                <svg className="w-auto h-6 block overflow-hidden" data-ditto-id="style-image" data-component="icon" aria-describedby="location_icon" aria-hidden="true" fill="none" height="24" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg">
                                  <title id="location_icon">
                                    {"Location Icon"}
                                  </title>
                                  <path d="M12 2C14.1217 2 16.1566 2.86721 17.6569 4.41084C19.1571 5.95448 20 8.0481 20 10.2311C20 13.7093 17.6246 17.4999 12.9354 21.6433C12.6746 21.8737 12.3422 22.0003 11.9985 22C11.6547 21.9997 11.3225 21.8725 11.0622 21.6416L10.752 21.3647C6.27036 17.3293 4 13.6316 4 10.2311C4 8.0481 4.84285 5.95448 6.34315 4.41084C7.84344 2.86721 9.87827 2 12 2ZM12 3.26633C10.2047 3.26633 8.48291 4.00012 7.21343 5.30627C5.94395 6.61243 5.23077 8.38395 5.23077 10.2311C5.23077 13.1876 7.32144 16.594 11.5602 20.4099L11.8663 20.6826C11.9035 20.7155 11.9509 20.7336 12 20.7336C12.0491 20.7336 12.0965 20.7155 12.1337 20.6826C16.5776 16.7553 18.7692 13.2577 18.7692 10.2311C18.7692 9.3165 18.5941 8.41083 18.254 7.56582C17.9138 6.72081 17.4152 5.95301 16.7866 5.30627C16.158 4.65953 15.4118 4.14651 14.5905 3.79649C13.7692 3.44648 12.8889 3.26633 12 3.26633ZM12 7.06531C12.8161 7.06531 13.5987 7.39885 14.1757 7.99256C14.7527 8.58626 15.0769 9.3915 15.0769 10.2311C15.0769 11.0708 14.7527 11.876 14.1757 12.4697C13.5987 13.0634 12.8161 13.397 12 13.397C11.1839 13.397 10.4013 13.0634 9.82429 12.4697C9.24725 11.876 8.92308 11.0708 8.92308 10.2311C8.92308 9.3915 9.24725 8.58626 9.82429 7.99256C10.4013 7.39885 11.1839 7.06531 12 7.06531ZM12 8.33164C11.5104 8.33164 11.0408 8.53176 10.6946 8.88799C10.3484 9.24421 10.1538 9.72735 10.1538 10.2311C10.1538 10.7349 10.3484 11.2181 10.6946 11.5743C11.0408 11.9305 11.5104 12.1306 12 12.1306C12.4896 12.1306 12.9592 11.9305 13.3054 11.5743C13.6516 11.2181 13.8462 10.7349 13.8462 10.2311C13.8462 9.72735 13.6516 9.24421 13.3054 8.88799C12.9592 8.53176 12.4896 8.33164 12 8.33164Z" fill="black" />
                                </svg>
                              </div>
                              <div className="block">
                                <div className="block mr-2 [font-family:regola-neue-semibold,_sans-serif] text-xs leading-[1rem]">
                                  Ship to
                                </div>
                                <div className="overflow-hidden text-xs leading-[1rem] underline line-clamp-1">
                                  {" Please enter an Address"}
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className="flex items-center shrink-0">
                        <div className="block relative">
                          <div className="flex items-center shrink-0 max-md:hidden" data-ditto-id="style-div-12" data-component="button" aria-label="login" role="button">
                            <img className="w-10 h-6 block max-w-full px-2 overflow-clip cursor-pointer" data-ditto-id="style-heading-17" data-component="image" alt="My Account" src="/assets/cloned/svg/95449e8a8d0f.svg" />
                          </div>
                        </div>
                        <div className="flex relative bg-background" data-component="button" aria-label="Go to cart" role="button">
                          <img className="w-9.5 h-5 block max-w-full px-2 overflow-clip cursor-pointer" data-ditto-id="style-span" data-component="image" alt="" src={iconFor("Go to cart")} />
                        </div>
                      </div>
                    </div>
                  </nav>
                </div>
              </header>
              <main className="block" id="maincontent">
                <div className="block text-center" data-ditto-id="style-font">
                  <div className="hidden relative bg-background">
                    <div className="w-full block absolute top-0 left-0 bg-clr-6 mx-auto" />
                  </div>
                  <div className="min-h-187.5 block relative min-w-200 max-w-2500 max-h-187.5 max-lg:min-h-175 max-lg:min-w-90 max-lg:max-h-175" data-ditto-id="style-div-34" aria-label="Inline Form" id="lightbox-dac0f2e5-c7f4-4568-b018-23747dd578b4-1784916096846" role="dialog">
                    <iframe className="w-320 h-187.5 block absolute overflow-clip max-md:w-[23.4375rem] max-lg:h-175 md:max-lg:w-192" data-ditto-id="style-heading-28" aria-label="Modal Overlay Box Frame" height="100%" id="lightbox-iframe-dac0f2e5-c7f4-4568-b018-23747dd578b4" title="Pressed Quiz (updated version)" width="100%" />
                  </div>
                </div>
              </main>
            </div>
            <footer className="block py-20 text-background bg-foreground max-lg:pt-10 max-lg:pb-16" data-ditto-id="style-br-23">
              <div className="h-full block" data-ditto-id="style-p-49">
                <div className="h-full block max-w-360 px-16 mx-auto max-md:px-6 md:max-lg:px-8" data-ditto-id="style-p-25">
                  <div className="border-b border-solid border-b-background grid mb-6 pb-10 gap-x-[5%] grid-cols-[40px_162px_minmax(0,1fr)] max-lg:block max-lg:grid-cols-[40px_162px_auto] max-lg:border-b-[0] max-lg:border-initial max-lg:border-b-[initial] max-lg:pb-0" data-ditto-id="style-p-22">
                    <a className="h-11 block mb-10 cursor-pointer max-lg:inline-block" data-ditto-id="style-strong-6" data-component="link" href="/">
                      <img className="w-10 h-10 inline max-w-full overflow-clip" data-ditto-id="style-link-10" data-component="image" alt="Pressed Juicery logo" src={iconFor("Pressed Juicery logo")} />
                    </a>
                    <div className="block" data-ditto-id="style-strong-7">
                      <form className="block mb-6" data-ditto-id="style-link-11">
                        <div className="w-full block md:max-lg:w-[61%]" data-ditto-id="style-strong-8">
                          <h2 className="block mb-3 [font-family:regola-neue-semibold,_sans-serif] leading-[1.1875rem]" data-ditto-id="style-link-12" data-component="heading">
                            Sign up for our newsletter
                          </h2>
                          <div className="block mb-3 text-sm leading-4" data-ditto-id="style-br-12">
                            Get the latest news and offers by signing up for our newsletter!
                          </div>
                          <div className="block mb-3" data-ditto-id="style-link" aria-label="Enter your email to sign up for our newsletter">
                            <div className="block mb-1 leading-3.5" data-ditto-id="style-div-91" id="lbl_v-0-0">
                              <label className="inline [font-family:regola-neue-semibold,_sans-serif] leading-6 cursor-default" data-ditto-id="style-figure-11" htmlFor="v-0-0">
                                Enter your email
                              </label>
                            </div>
                            <input className="w-full h-10.5 border-2 border-solid border-background block mb-3 py-2 px-4 rounded-[10px] overflow-clip leading-4 tracking-[normal] cursor-text" data-ditto-id="style-div-92" data-component="input" aria-describedby="error_v-0-0" aria-label="Enter your email to sign up for our newsletter" id="v-0-0" />
                          </div>
                          <button className="h-10 border-2 border-solid border-background flex pt-2 pb-3 px-4 rounded-full justify-center items-center leading-[1.125rem] tracking-[normal] text-center whitespace-nowrap bg-foreground cursor-pointer" data-ditto-id="style-link-13" data-component="button" aria-label="Submit entered email to sign up for our newsletter" role="button" type="submit">
                            {" Sign Up"}
                          </button>
                        </div>
                      </form>
                      <div className="block max-lg:hidden" data-ditto-id="style-image-5">
                        <h2 className="block pb-2 [font-family:regola-neue-semibold,_sans-serif]" data-ditto-id="style-div-77" data-component="heading">
                          Get the App
                        </h2>
                        <ul className="grid [list-style-type:none] grid-cols-1">
                          <li className="list-item pb-2" data-ditto-id="style-div-150">
                            <a className="inline cursor-pointer" data-ditto-id="style-div-78" data-component="link" href="https://apps.apple.com/us/app/pressed-juicery/id1529648960" rel="noopener" target="_blank">
                              <img className="w-36 h-12 inline max-w-full overflow-clip" data-ditto-id="style-p-6" data-component="image" alt="download from the App Store" src="/assets/cloned/svg/9bccd60d7d6e.svg" />
                            </a>
                          </li>
                          <li className="list-item" data-ditto-id="style-div-28">
                            <a className="inline cursor-pointer" data-ditto-id="style-hr-4" data-component="link" href="https://play.google.com/store/apps/details?id=com.pressedjuicery.app" rel="noopener" target="_blank">
                              <img className="w-40.5 h-12 inline max-w-full overflow-clip" data-ditto-id="motion-div" data-component="image" alt="download from Google Play" src="/assets/cloned/svg/fbffbc22336d.svg" />
                            </a>
                          </li>
                        </ul>
                      </div>
                    </div>
                    <div className="grid gap-x-[5%] grid-cols-[3224fr_1184fr_1475fr_1097fr_3100fr] max-lg:block max-lg:mb-6 max-lg:grid-cols-[auto_auto_auto_auto_auto]" data-ditto-id="style-p-14">
                      <div className="block max-lg:border-b max-lg:border-solid max-lg:border-b-background max-lg:mb-6 max-lg:pb-6" data-ditto-id="style-div-93">
                        <h2 className="block pb-2 [font-family:regola-neue-semibold,_sans-serif]" data-ditto-id="style-div-21" data-component="heading">
                          Membership
                        </h2>
                        <div className="block pb-4" data-ditto-id="style-heading-19">
                          {" Enjoy VIP pricing and earn treats when you subscribe to a Pressed Juicery® Membership."}
                        </div>
                        <a className="inline rounded-xs underline cursor-pointer" data-ditto-id="style-strong-37" data-component="link" href="/juice-subscription-membership/signup">
                          {" Sign Up"}
                        </a>
                      </div>
                      <div className="block max-lg:border-b max-lg:border-solid max-lg:border-b-background max-lg:mb-6 max-lg:pb-6" data-ditto-id="style-br-55">
                        <h2 className="block pb-2 [font-family:regola-neue-semibold,_sans-serif]" data-ditto-id="style-div-119" data-component="heading">
                          Shop
                        </h2>
                        <ul className="flex flex-col [list-style-type:none] max-lg:flex-wrap max-lg:gap-[4%] max-lg:[flex-direction:initial]">
                          {ListRow2_data.map((d, i) => <ListRow2 key={i} d={d} styles={ListRow2_styles[i]} />)}
                        </ul>
                      </div>
                      <div className="block max-lg:border-b max-lg:border-solid max-lg:border-b-background max-lg:mb-6 max-lg:pb-6" data-ditto-id="style-div-115">
                        <h2 className="block pb-2 [font-family:regola-neue-semibold,_sans-serif]" data-ditto-id="style-div-95" data-component="heading">
                          Learn
                        </h2>
                        <ul className="flex flex-col [list-style-type:none] max-lg:flex-wrap max-lg:gap-[4%] max-lg:[flex-direction:initial]" data-ditto-id="style-div-29">
                          {ListRow3_data.map((d, i) => <ListRow3 key={i} d={d} styles={ListRow3_styles[i]} />)}
                        </ul>
                      </div>
                      <div className="block max-lg:border-b max-lg:border-solid max-lg:border-b-background max-lg:mb-6 max-lg:pb-6" data-ditto-id="style-div-30">
                        <h2 className="block pb-2 [font-family:regola-neue-semibold,_sans-serif]" data-ditto-id="style-div-27" data-component="heading">
                          Support
                        </h2>
                        <ul className="flex flex-col [list-style-type:none] max-lg:flex-wrap max-lg:gap-[4%] max-lg:[flex-direction:initial]" data-ditto-id="style-p-38">
                          {ListRow2_data2.map((d, i) => <ListRow2 key={i} d={d} styles={ListRow2_styles2[i]} />)}
                        </ul>
                      </div>
                      <div className="block max-lg:border-b max-lg:border-solid max-lg:border-b-background max-lg:mb-6 max-lg:pb-6" data-ditto-id="style-figure-12">
                        <h2 className="block pb-2 [font-family:regola-neue-semibold,_sans-serif]" data-ditto-id="style-div-22" data-component="heading">
                          Policies
                        </h2>
                        <ul className="flex flex-col [list-style-type:none] max-lg:flex-wrap max-lg:gap-[4%] max-lg:[flex-direction:initial]" data-ditto-id="style-image-11">
                          {ListRow4_data.map((d, i) => <ListRow4 key={i} d={d} styles={ListRow4_styles[i]} />)}
                        </ul>
                      </div>
                    </div>
                    <div className="hidden min-w-0 max-lg:block max-lg:mb-6 max-lg:justify-between max-lg:items-end" data-ditto-id="style-p-9">
                      <div className="block" data-ditto-id="style-link-2">
                        <h2 className="block pb-2 [font-family:regola-neue-semibold,_sans-serif]" data-ditto-id="style-div-23">
                          Get the App
                        </h2>
                        <ul className="grid grid-cols-[auto] [list-style-type:none] max-lg:flex max-lg:mb-10 max-lg:items-start" data-ditto-id="style-div-13">
                          <li className="list-item min-w-0 pb-2" data-ditto-id="style-p-15">
                            <a className="inline cursor-pointer max-lg:mr-6" data-ditto-id="style-div-97" href="https://apps.apple.com/us/app/pressed-juicery/id1529648960" rel="noopener" target="_blank">
                              <img className="inline max-w-full overflow-clip max-lg:w-36 max-lg:h-12" data-ditto-id="style-hr-2" alt="download from the App Store" src="/assets/cloned/svg/9bccd60d7d6e.svg" />
                            </a>
                          </li>
                          <li className="list-item min-w-0" data-ditto-id="style-div-33">
                            <a className="inline cursor-pointer max-lg:mr-6" data-ditto-id="style-p-16" href="https://play.google.com/store/apps/details?id=com.pressedjuicery.app" rel="noopener" target="_blank">
                              <img className="inline max-w-full overflow-clip max-lg:w-40.5 max-lg:h-12" data-ditto-id="style-div-14" alt="download from Google Play" src="/assets/cloned/svg/fbffbc22336d.svg" />
                            </a>
                          </li>
                        </ul>
                      </div>
                      <ul className="hidden [list-style-type:none] max-lg:flex" data-ditto-id="style-div-128">
                        {Logo2_data.map((d, i) => <Logo2 key={i} d={d} styles={Logo2_styles[i]} />)}
                      </ul>
                    </div>
                  </div>
                  <div className="flex justify-between max-lg:mb-1" data-ditto-id="style-p-18">
                    <div className="flex max-lg:flex-col" data-ditto-id="style-br-20">
                      <div className="block mr-6 max-lg:mb-2" data-ditto-id="style-br-2">
                        Ⓒ 2026 Pressed Juicery®
                      </div>
                      <ul className="flex [list-style-type:none] max-lg:flex-col" data-ditto-id="style-br-21">
                        {ListRow5_data.map((d, i) => <ListRow5 key={i} d={d} styles={ListRow5_styles[i]} />)}
                      </ul>
                    </div>
                    <ul className="flex [list-style-type:none] max-lg:hidden" data-ditto-id="style-br-5">
                      {Logo3_data.map((d, i) => <Logo3 key={i} d={d} styles={Logo3_styles[i]} />)}
                    </ul>
                  </div>
                  <div className="block" data-ditto-id="style-link-4">
                    <a className="inline mr-6 cursor-pointer" data-ditto-id="style-br-17" data-component="link" href="https://pressed.com/legal/sensitive-personal-information-statement">
                      {" Limit the Use of My Sensitive Personal Information"}
                    </a>
                  </div>
                </div>
              </div>
            </footer>
          </div>
        </div>
      </div>
      <div className="block" data-ditto-id="style-p-10" id="teleports" />
      <div className="block" data-ditto-id="style-div-26" />
      <iframe className="w-px h-px block absolute -top-[624.9375rem] overflow-clip" aria-hidden="true" role="presentation" title="Blank" />
      <div className="w-[34.1094px] h-5.5 block absolute -top-[6249.9375rem] -left-[6249.9375rem] leading-5.5 whitespace-nowrap" data-ditto-id="style-figure-14">
        Mgy
      </div>
      <DittoMotion spec={{"waapi":[],"rotators":[],"reveals":[{"anchor":"motion-picture","opacity":"0","transform":"none","transition":"opacity 0.5s"}],"marquees":[]}} />
      <DropdownMenu menus={[{"trigger":"style-shop-dropdown-2","hoverOpen":false,"gap":0,"align":"right","html":"<div style=\"position:absolute;margin:0;display:block;box-sizing:border-box;width:304px;height:800px;min-width:0px;max-width:none;min-height:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px;border-top-width:0px;border-right-width:0px;border-bottom-width:0px;border-left-width:0px;border-top-style:none;border-right-style:none;border-bottom-style:none;border-left-style:none;border-top-color:rgb(0, 0, 0);border-right-color:rgb(0, 0, 0);border-bottom-color:rgb(0, 0, 0);border-left-color:rgb(0, 0, 0);border-top-left-radius:0px;border-top-right-radius:0px;border-bottom-right-radius:0px;border-bottom-left-radius:0px;background-color:rgb(255, 255, 255);color:rgb(0, 0, 0);box-shadow:none;opacity:1;font-family:regola-neue-regular, sans-serif;font-size:16px;font-weight:400;font-style:normal;line-height:24px;letter-spacing:0.54px;text-align:start;text-transform:none;text-decoration-line:none;white-space:normal;flex-direction:row;flex-wrap:nowrap;justify-content:normal;align-items:normal;gap:normal;row-gap:normal;column-gap:normal;grid-template-columns:none;grid-template-rows:none;list-style-type:disc;vertical-align:baseline;object-fit:fill;cursor:auto;overflow:auto\"></div>"}]} />
    </>
  );
}
