import { iconFor } from "../_icons";
import"./ditto.css";
import DropdownMenu from"../ditto/DropdownMenu";
import Logo from"./components/logo";
import ListRow from"./components/list-row";
import MediaTile from"./components/media-tile";
import MediaTile2 from"./components/media-tile2";
import ListRow2 from"./components/list-row2";
import ListRow3 from"./components/list-row3";
import ListRow4 from"./components/list-row4";
import Logo2 from"./components/logo2";
import ListRow5 from"./components/list-row5";
import Logo3 from"./components/logo3";
// Generated by clone-site. Do not edit by hand.
const Logo_data = [
    { ariaLabel:"View previous offer" },
    { ariaLabel:"View next offer" },
    { ariaLabel:"Pause offer carousel" }
];
const ListRow_data = [
    { href:"https://pressed.com/our-journey", label:"About" },
    { href:"https://pressed.com/juice-subscription-membership/signup", label:"Pressed Rewards" },
    { href:"/juice-bar-locations", label:"Find a Store" },
    { href:"/flavor-quiz", label:"Quiz" },
    { href:"/catering", label:"Catering" }
];
const MediaTile_data = [
    { height:"640", imgSrc:"/assets/cloned/images/2976c7d618f2.png", width:"608", description:"Spinach" },
    { height:"638", imgSrc:"/assets/cloned/images/181dfa41c57f.png", width:"610", description:"Kale" },
    { height:"640", imgSrc:"/assets/cloned/images/a5c4e697bdd1.png", width:"610", description:"Parsley" },
    { height:"640", imgSrc:"/assets/cloned/images/f3bb500dd97d.png", width:"610", description:"Cucumber" }
];
const MediaTile2_data = [
    { imgSrc:"/assets/cloned/images/7be9a6c66794.png", description:"Ginger" },
    { imgSrc:"/assets/cloned/images/a8238b3c5132.png", description:"Lemon" },
    { imgSrc:"/assets/cloned/images/1f54a20a173f.png", description:"Turmeric" },
    { imgSrc:"/assets/cloned/images/dc89023331cf.png", description:"Beets" }
];
const ListRow2_data = [
    { href:"https://pressed.com/shop", label:"Shop All" },
    { href:"/juice-bar-locations", label:"Find a Store" },
    { href:"/foodservice", label:"Wholesale" },
    { href:"/catering", label:"Catering" }
];
const ListRow3_data = [
    { href:"https://pressed.com/our-journey", label:"Our Story" },
    { href:"https://pressed.com/blogs/pressed-life", label:"Blog" },
    { href:"https://pressed.com/juice-cleanses", label:"Juice Cleanses" },
    { href:"/acai-bowls", label:"Acai Bowls" },
    { href:"/cleanse-guide", label:"Cleanse Guide" },
    { href:"https://pressed.com/juice-subscription-membership/signup", label:"Rewards" },
    { href:"/gut-biome-sulforaphane-benefits", label:"Gut Biome+" }
];
const ListRow2_data2 = [
    { href:"https://pressed.com/pages/contact-us", label:"Contact Us" },
    { href:"/faqs", label:"FAQs" },
    { href:"/allergens", label:"Nutrition" },
    { href:"/careers", label:"Careers" }
];
const ListRow4_data = [
    { href:"https://pressed.com/legal/shipping-policy", label:"Shipping & Delivery" },
    { href:"https://pressed.com/legal/refund-and-cancellation-policy", label:"Refund & Cancellation" },
    { href:"https://pressed.com/legal/member-terms-and-conditions", label:"Member Terms and Conditions" },
    { href:"https://pressed.com/legal/vip-terms-and-conditions", label:"VIP Terms and Conditions" },
    { href:"https://pressed.com/legal/accessibility-policy", label:"Accessibility Policy" }
];
const Logo2_data = [
    { href:"https://www.instagram.com/pressedjuicery/", alt:"Instagram" },
    { href:"https://www.facebook.com/PressedOfficial", alt:"Facebook" },
    { href:"https://x.com/pressedjuicery", alt:"Twitter" },
    { href:"https://www.youtube.com/channel/UC5E5Wd9hZaZoyJU25cKeRsg", alt:"YouTube" }
];
const ListRow5_data = [
    { href:"https://pressed.com/legal/terms-of-use", label:"Terms of Use" },
    { href:"https://pressed.com/legal/privacy-policy", label:"Privacy Policy" },
    { href:"javascript:Cookiebot.show()", label:"Do Not Sell or Share My Personal Information" }
];
const Logo3_data = [
    { href:"https://www.instagram.com/pressedjuicery/", alt:"Instagram" },
    { href:"https://www.facebook.com/PressedOfficial", alt:"Facebook" },
    { href:"https://x.com/pressedjuicery", alt:"Twitter" },
    { href:"https://www.youtube.com/channel/UC5E5Wd9hZaZoyJU25cKeRsg", alt:"YouTube" }
];
const Logo_meta: string[][] = [
    ["style-link-9","n15"],
    ["style-div-3","n17"],
    ["style-div-4","n19"]
];
const ListRow_meta: string[][] = [
    ["n33","style-pressed-juicery-home-2"],
    ["n35","style-source"],
    ["n37","style-ul-3"],
    ["n39","style-div-5"],
    ["style-shop-dropdown-2","style-33"]
];
const MediaTile_meta: string[][] = [
    ["n118","style-div-116","style-div-96","style-a-5","style-u","style-br-65"],
    ["n124","style-strong-39","n126","style-p-46","style-a","style-p-50"],
    ["n130","style-h3-6","style-div-30","style-div-27","style-p-38","style-figure-13"],
    ["style-div-117","style-image-10","style-heading-3","style-strong-2","style-p-7","style-div-31"]
];
const MediaTile2_meta: string[][] = [
    ["style-figure-12","style-div-22","style-image-11","style-heading-22","style-strong-3","style-p-60"],
    ["style-div-118","style-p-8","style-figure-2","style-div-32","style-image-4","style-heading-7"],
    ["style-strong-40","style-p-9","style-link-2","style-div-23","style-div-13","style-p-15"],
    ["style-div-97","style-hr-2","style-div-33","style-p-16","style-div-14","style-div-128"]
];
const ListRow2_meta: string[][] = [
    ["style-div-70","style-div-59"],
    ["n278","style-div-35"],
    ["style-hr-3","style-div-60"],
    ["n282","style-div-61"]
];
const ListRow3_meta: string[][] = [
    ["style-link-17","style-image-7"],
    ["style-heading-20","style-strong-18"],
    ["style-p-39","style-div-62"],
    ["n293","style-heading-14"],
    ["style-strong-22","style-br-37"],
    ["style-p-40","style-div-63"],
    ["style-heading-27","style-strong-19"]
];
const ListRow2_meta2: string[][] = [
    ["n304","style-strong-20"],
    ["style-br-42","style-p-36"],
    ["n308","style-heading-15"],
    ["n310","style-br-24"]
];
const ListRow4_meta: string[][] = [
    ["style-div-143","style-div-64"],
    ["n317","style-div-65"],
    ["n319","style-div-66"],
    ["style-p-27","style-div-67"],
    ["style-div-82","style-heading-16"]
];
const Logo2_meta: string[][] = [
    ["style-br-43","style-br-70","style-br-44"],
    ["style-strong-25","style-br-45","style-br-51"],
    ["style-br-46","style-strong-9","style-br-25"],
    ["style-br-74","style-br-47","style-strong-48"]
];
const ListRow5_meta: string[][] = [
    ["style-strong-27","style-br-26"],
    ["style-link-19","style-br-38"],
    ["style-link-20","style-u-2"]
];
const Logo3_meta: string[][] = [
    ["style-br-49","style-strong-21","style-br-58"],
    ["style-br-67","style-link-21","style-u-3"],
    ["n365","style-br-39","n367"],
    ["style-br-50","style-br-40","style-link-22"]
];
const Logo_styles = [
    { className:"w-2 h-3" },
    { className:"w-2 h-3" },
    { className:"w-3.5 h-4" }
];
const MediaTile_styles = [
    { className:"grid-rows-[calc(0.848vw_+_120.296px)_0px] max-md:grid-rows-[calc(27.322vw_-_8.175px)_0px] md:max-lg:grid-rows-[calc(27.332vw_-_8.222px)_0px]", className2:"aspect-[1.83]", className3:"h-[8.1875rem] aspect-[auto_608/640] max-md:h-23.5 md:max-lg:h-50.5" },
    { className:"grid-rows-[calc(1.294vw_+_183.373px)_0px] max-md:grid-rows-[calc(41.651vw_-_12.474px)_0px] md:max-lg:grid-rows-[calc(41.663vw_-_12.536px)_0px]", className2:"aspect-[1.2]", className3:"h-50 aspect-[auto_610/638] max-md:h-36 md:max-lg:h-[19.1875rem]" },
    { className:"grid-rows-[calc(1.55vw_+_220.124px)_0px] max-lg:grid-rows-[calc(50vw_-_15px)_0px]", className2:"aspect-square", className3:"h-60 aspect-[auto_610/640] max-md:h-[10.8125rem] md:max-lg:h-[23.0625rem]" },
    { className:"grid-rows-[calc(1.098vw_+_155.502px)_0px] max-md:grid-rows-[calc(35.327vw_-_10.584px)_0px] md:max-lg:grid-rows-[calc(35.327vw_-_10.574px)_0px]", className2:"aspect-[1.415]", className3:"h-42.5 aspect-[auto_610/640] max-md:h-30.5 md:max-lg:h-[16.3125rem]" }
];
const MediaTile2_styles = [
    { className:"grid-rows-[calc(1.428vw_+_203.314px)_0px] max-md:grid-rows-[calc(46.175vw_-_13.86px)_0px] md:max-lg:grid-rows-[calc(46.18vw_-_13.894px)_0px]", className2:"aspect-[1.083]", className3:"h-55.5 max-md:h-40 md:max-lg:h-[21.3125rem]" },
    { className:"grid-rows-[calc(1.294vw_+_184.049px)_0px] max-md:grid-rows-[calc(41.801vw_-_12.551px)_0px] md:max-lg:grid-rows-[calc(41.797vw_-_12.516px)_0px]", className2:"aspect-[1.196]", className3:"h-[12.5625rem] max-md:h-36 md:max-lg:h-77" },
    { className:"grid-rows-[calc(1.611vw_+_229.422px)_0px] max-md:grid-rows-[calc(52.098vw_-_15.618px)_0px] md:max-lg:grid-rows-[calc(52.112vw_-_15.708px)_0px]", className2:"aspect-[0.96]", className3:"h-62.5 max-md:h-45 md:max-lg:h-96" },
    { className:"grid-rows-[calc(1.288vw_+_182.546px)_0px] max-md:grid-rows-[calc(41.473vw_-_12.463px)_0px] md:max-lg:grid-rows-[calc(41.467vw_-_12.421px)_0px]", className2:"aspect-[1.206]", className3:"h-[12.4375rem] max-md:h-36 md:max-lg:h-76.5" }
];
const ListRow2_styles = [
    { className:"w-[92.7031px] pb-2 max-md:w-[150.406px] md:max-lg:w-[323.828px]" },
    { className:"w-[92.7px] pb-2 max-md:w-[calc(46.01vw_-_22.126px)] md:max-lg:w-[calc(46vw_-_29.45px)]" },
    { className:"w-[92.7031px] pb-2 max-md:w-[150.406px] md:max-lg:w-[323.828px]" },
    { className:"w-[92.7031px] max-md:w-[150.406px] md:max-lg:w-[323.828px]" }
];
const ListRow3_styles = [
    { className:"pb-2 max-md:w-[150.406px] md:max-lg:w-[323.828px]" },
    { className:"pb-2 max-md:w-[150.406px] md:max-lg:w-[323.828px]" },
    { className:"pb-2 max-md:w-[calc(46.01vw_-_22.126px)] md:max-lg:w-[calc(46vw_-_29.45px)]" },
    { className:"pb-2 max-md:w-[150.406px] md:max-lg:w-[323.828px]" },
    { className:"pb-2 max-md:w-[calc(46.01vw_-_22.126px)] md:max-lg:w-[calc(46vw_-_29.45px)]" },
    { className:"pb-2 max-md:w-[150.406px] md:max-lg:w-[323.828px]" },
    { className:"max-md:w-[150.406px] md:max-lg:w-[323.828px]" }
];
const ListRow2_styles2 = [
    { className:"w-[5.37rem] pb-2 max-md:w-[calc(46.01vw_-_22.126px)] md:max-lg:w-[calc(46vw_-_29.45px)]" },
    { className:"w-[85.9219px] pb-2 max-md:w-[150.406px] md:max-lg:w-[323.828px]" },
    { className:"w-[85.9219px] pb-2 max-md:w-[150.406px] md:max-lg:w-[323.828px]" },
    { className:"w-[85.9219px] max-md:w-[150.406px] md:max-lg:w-[323.828px]" }
];
const ListRow4_styles = [
    { className:"pb-2" },
    { className:"pb-2" },
    { className:"pb-2" },
    { className:"pb-2" },
    {  }
];
const Logo2_styles = [
    { className:"mr-4", className2:"max-lg:w-6 max-lg:h-6" },
    { className:"mr-4", className2:"max-lg:w-3 max-lg:h-6" },
    { className:"mr-4", className2:"max-lg:w-6 max-lg:h-5" },
    { className2:"max-lg:w-6 max-lg:h-4" }
];
const ListRow5_styles = [
    { className:"mr-6" },
    { className:"mr-6" },
    {  }
];
const Logo3_styles = [
    { className:"mr-4", className2:"w-6 h-6" },
    { className:"mr-4", className2:"w-3 h-6" },
    { className:"mr-4", className2:"w-6 h-5" },
    { className2:"w-6 h-4" }
];

export default function Page() {
  return (
    <>
      <div className="block" id="__nuxt">
        <div className="block">
          <div className="min-h-screen grid grid-cols-1">
            <div className="block" data-ditto-id="style-default-layout-header-wrapper" id="default-layout-header-wrapper">
              <a className="w-[244.828px] h-11.5 border-r border-solid border-r-color-003 border-b border-b-color-003 block absolute -top-12 z-101 pt-1.5 pb-0.5 px-1.5 overflow-hidden text-2xl leading-9 bg-background cursor-pointer" data-component="link" href="#maincontent">
                Skip to main content
              </a>
              <header className="h-[8.6875rem] block sticky top-0 z-100 max-md:h-[9.4375rem] md:max-lg:h-[8.1875rem]" data-ditto-id="style-pressed-header" id="pressed-header">
                <div className="min-h-10 block py-3 text-background [font-family:regola-neue-medium,_sans-serif] bg-foreground max-md:h-15 max-md:flex max-md:py-1 max-md:items-center">
                  <div className="block max-w-360 px-16 mx-auto max-md:px-6 md:max-lg:px-8" data-ditto-id="style-div-6">
                    <div className="flex justify-between items-center">
                      <div className="flex px-4 flex-wrap justify-center grow gap-1 text-center max-md:flex-col max-lg:items-center max-lg:[font-family:regola-neue-semibold,_sans-serif] max-lg:text-xs max-lg:leading-[1rem] max-md:gap-[initial]" aria-label="View all offers Carousel" aria-live="polite" role="region">
                        <span className="overflow-hidden line-clamp-1 max-md:line-clamp-3">
                          Free Local Delivery on Orders $60+
                        </span>
                        <span className="block ml-4 underline whitespace-nowrap cursor-pointer max-lg:ml-0" data-ditto-id="style-viewallofferselement" data-component="button" id="viewAllOffersElement" role="button">
                          {" View All Offers"}
                        </span>
                      </div>
                      <div className="flex shrink-0" data-ditto-id="style-div-7">
                        {Logo_data.map((d, i) => <Logo key={i} d={d} styles={Logo_styles[i]} />)}
                      </div>
                    </div>
                  </div>
                </div>
                <div className="block py-6 px-8 bg-background shadow-[var(--clr-0)_0px_0px_10px_0px]">
                  <nav className="h-11 flex sticky top-0 justify-between" data-ditto-id="style-nav" data-component="nav">
                    <div className="flex items-center shrink-0">
                      <div className="block" data-ditto-id="style-div-8">
                        <img className="hidden max-w-full overflow-clip max-lg:w-6 max-lg:h-6 max-lg:inline-block" alt="Menu" role="button" src={iconFor("Menu")} />
                      </div>
                      <a className="block cursor-pointer aspect-[3.605] max-lg:aspect-[1.86]" data-ditto-id="style-pressed-juicery-home" data-component="link" aria-label="Pressed Juicery Home" href="/">
                        <picture className="inline" data-ditto-id="motion-picture">
                          <source className="inline" data-ditto-id="style-source-2" media="(min-width: 1000px)" srcSet="/assets/cloned/images/pressed-wordmark.png" />
                          <img className="w-[9.6875rem] h-9.5 inline max-w-full px-4 overflow-clip max-lg:w-20" data-ditto-id="motion-image" data-component="image" src={iconFor("Pressed Juicery Home")} />
                        </picture>
                      </a>
                      <ul className="flex mx-4 gap-4 [list-style-type:none] max-lg:hidden" data-ditto-id="motion-ul">
                        <li className="list-item p-2">
                          <div className="block relative cursor-pointer">
                            <a className="inline" data-ditto-id="style-shop-dropdown" data-component="link" aria-expanded="false" aria-haspopup="menu" aria-label="Shop dropdown" href="https://pressed.com/shop">
                              Shop
                            </a>
                          </div>
                        </li>
                        {ListRow_data.map((d, i) => <ListRow key={i} d={d} />)}
                      </ul>
                    </div>
                    <div className="flex items-center gap-4" data-ditto-id="style-div-9">
                      <div className="flex justify-end items-center cursor-pointer">
                        <div className="block" data-ditto-id="style-div-10">
                          <div className="block">
                            <div className="flex items-center" data-ditto-id="style-button" data-component="button" role="button">
                              <div className="h-4 flex mr-2 items-center">
                                <svg className="w-auto h-6 block overflow-hidden" data-ditto-id="style-icon" data-component="icon" aria-describedby="location_icon" aria-hidden="true" fill="none" height="24" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg">
                                  <title id="location_icon">
                                    {"Location Icon"}
                                  </title>
                                  <path d="M12 2C14.1217 2 16.1566 2.86721 17.6569 4.41084C19.1571 5.95448 20 8.0481 20 10.2311C20 13.7093 17.6246 17.4999 12.9354 21.6433C12.6746 21.8737 12.3422 22.0003 11.9985 22C11.6547 21.9997 11.3225 21.8725 11.0622 21.6416L10.752 21.3647C6.27036 17.3293 4 13.6316 4 10.2311C4 8.0481 4.84285 5.95448 6.34315 4.41084C7.84344 2.86721 9.87827 2 12 2ZM12 3.26633C10.2047 3.26633 8.48291 4.00012 7.21343 5.30627C5.94395 6.61243 5.23077 8.38395 5.23077 10.2311C5.23077 13.1876 7.32144 16.594 11.5602 20.4099L11.8663 20.6826C11.9035 20.7155 11.9509 20.7336 12 20.7336C12.0491 20.7336 12.0965 20.7155 12.1337 20.6826C16.5776 16.7553 18.7692 13.2577 18.7692 10.2311C18.7692 9.3165 18.5941 8.41083 18.254 7.56582C17.9138 6.72081 17.4152 5.95301 16.7866 5.30627C16.158 4.65953 15.4118 4.14651 14.5905 3.79649C13.7692 3.44648 12.8889 3.26633 12 3.26633ZM12 7.06531C12.8161 7.06531 13.5987 7.39885 14.1757 7.99256C14.7527 8.58626 15.0769 9.3915 15.0769 10.2311C15.0769 11.0708 14.7527 11.876 14.1757 12.4697C13.5987 13.0634 12.8161 13.397 12 13.397C11.1839 13.397 10.4013 13.0634 9.82429 12.4697C9.24725 11.876 8.92308 11.0708 8.92308 10.2311C8.92308 9.3915 9.24725 8.58626 9.82429 7.99256C10.4013 7.39885 11.1839 7.06531 12 7.06531ZM12 8.33164C11.5104 8.33164 11.0408 8.53176 10.6946 8.88799C10.3484 9.24421 10.1538 9.72735 10.1538 10.2311C10.1538 10.7349 10.3484 11.2181 10.6946 11.5743C11.0408 11.9305 11.5104 12.1306 12 12.1306C12.4896 12.1306 12.9592 11.9305 13.3054 11.5743C13.6516 11.2181 13.8462 10.7349 13.8462 10.2311C13.8462 9.72735 13.6516 9.24421 13.3054 8.88799C12.9592 8.53176 12.4896 8.33164 12 8.33164Z" fill="black" />
                                </svg>
                              </div>
                              <div className="block">
                                <div className="block mr-2 [font-family:regola-neue-semibold,_sans-serif] text-xs leading-[1rem]" data-ditto-id="style-div-11">
                                  Ship to
                                </div>
                                <div className="overflow-hidden text-xs leading-[1rem] underline line-clamp-1">
                                  {" Please enter an Address"}
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className="flex items-center shrink-0">
                        <div className="block relative">
                          <div className="flex items-center shrink-0 max-md:hidden" data-ditto-id="style-login" data-component="button" aria-label="login" role="button">
                            <img className="w-10 h-6 block max-w-full px-2 overflow-clip cursor-pointer" data-ditto-id="style-image-2" data-component="image" alt="My Account" src="/assets/cloned/svg/95449e8a8d0f.svg" />
                          </div>
                        </div>
                        <div className="flex relative bg-background" data-component="button" aria-label="Go to cart" role="button">
                          <img className="w-9.5 h-5 block max-w-full px-2 overflow-clip cursor-pointer" data-ditto-id="style-image" data-component="image" alt="" src={iconFor("Go to cart")} />
                        </div>
                      </div>
                    </div>
                  </nav>
                </div>
              </header>
              <main className="block" id="maincontent">
                <div className="block">
                  <div className="block">
                    <div className="block mx-auto">
                      <div className="grid relative pl-5 grid-cols-[1fr_1020px_1fr] [grid-auto-rows:max-content] leading-4 bg-background mx-auto max-lg:pl-2.5 max-lg:grid-cols-[auto_1fr_auto]">
                        <div className="grid min-w-0 mb-6.5 -mx-5 px-5 justify-center gap-x-5 col-span-full bg-[rgb(222,216,190)] grid-cols-12 max-lg:hidden" data-ditto-id="style-div-12">
                          <div className="flex min-w-0 flex-col basis-[calc(600%_+_100px)] col-start-[span_6]" data-ditto-id="style-heading-17">
                            <p className="box-content min-h-6 block mb-6.5 shrink-0 [font-family:FTRegolaNeue-Regular,_stk] leading-[1.5625rem] tracking-[normal] [overflow-wrap:break-word] [pointer-events:all]" />
                            <p className="box-content min-h-18 block mb-6.5 shrink-0 [font-family:FTRegolaNeue-Regular,_stk] text-6xl leading-18 tracking-[normal] text-center [overflow-wrap:break-word] [pointer-events:all]" data-ditto-id="style-span">
                              {" Cold-Pressed Juices"}
                            </p>
                            <p className="box-content min-h-8 block mb-6.5 px-7.5 shrink-0 [font-family:grenette-regular-pro,_stk] text-xl leading-8 tracking-[normal] text-center [overflow-wrap:break-word] [pointer-events:all]">
                              Crafted with premium produce harvested at the peak of freshness, our cold-pressed juices are packed with fresh ingredients and bursting with refreshing flavor.
                            </p>
                            <a className="box-content w-[145.938px] min-h-5.5 block px-6 rounded-[40px] self-center [justify-self:center] shrink-0 text-background [font-family:FTRegolaNeueBETA-Semibold,_stk] leading-11.5 tracking-[normal] text-center [overflow-wrap:break-word] bg-foreground cursor-pointer [pointer-events:all]" data-ditto-id="style-font" data-component="link" href="https://pressed.com/shop">
                              Shop Popular Juices
                            </a>
                          </div>
                          <div className="flex min-w-0 flex-col basis-[calc(600%_+_100px)] col-start-[span_6]">
                            <figure className="box-content h-full grid relative max-w-full shrink-0 [overflow-wrap:break-word] [pointer-events:all] grid-cols-1">
                              <div className="box-content h-[clamp(509.78px,_65vh,_518.02px)] block col-start-1 row-start-1 overflow-hidden [pointer-events:all]" data-ditto-id="style-div-34">
                                <img className="box-content w-125 h-129.5 inline max-w-full aspect-[auto_1438/1490] align-top [pointer-events:all]" data-ditto-id="style-heading-28" data-component="image" height="1490" src="/assets/cloned/images/6714bd16015c.png" width="1438" />
                              </div>
                            </figure>
                            {""}
                          </div>
                        </div>
                        <div className="hidden min-w-0 mb-6.5 -mx-5 px-5 justify-center gap-x-5 grid-cols-[repeat(12,_minmax(0px,_66.6667px))] col-span-full bg-[rgb(222,216,190)] bg-contain [background-position:50%_0%] bg-no-repeat max-lg:grid max-lg:-mx-2.5 max-lg:px-2.5 max-lg:flex-col max-lg:justify-stretch max-lg:gap-y-5 max-lg:grid-cols-1" style={{ backgroundImage:"url(\"/assets/cloned/images/6714bd16015c.png\")" }} data-ditto-id="style-br-23">
                          <div className="flex flex-col basis-[calc(1200%_+_220px)] col-start-[span_12] text-center max-lg:min-w-0 max-lg:col-start-[span_1] max-lg:basis-[initial]" data-ditto-id="style-p-49">
                            <p className="box-content min-h-6 block min-w-0 mb-26 shrink-0 [font-family:FTRegolaNeue-Regular,_stk] leading-[1.5625rem] tracking-[normal] [overflow-wrap:break-word] [pointer-events:all]" data-ditto-id="style-p-25" />
                            <p className="box-content min-h-6 block min-w-0 mb-19.5 shrink-0 [font-family:FTRegolaNeue-Regular,_stk] leading-[1.5625rem] tracking-[normal] [overflow-wrap:break-word] [pointer-events:all]" data-ditto-id="style-p-22" />
                            <p className="box-content min-h-6 block min-w-0 mb-26 shrink-0 [font-family:FTRegolaNeue-Regular,_stk] leading-[1.5625rem] tracking-[normal] [overflow-wrap:break-word] [pointer-events:all]" data-ditto-id="style-strong-6" />
                            <p className="box-content min-h-6 block min-w-0 mb-13 shrink-0 [font-family:FTRegolaNeue-Regular,_stk] leading-[1.5625rem] tracking-[normal] [overflow-wrap:break-word] [pointer-events:all]" data-ditto-id="style-link-10" />
                            <p className="box-content min-h-18 block min-w-0 mb-6.5 shrink-0 [font-family:FTRegolaNeue-Regular,_stk] text-6xl leading-18 tracking-[normal] [overflow-wrap:break-word] [pointer-events:all] max-lg:text-left" data-ditto-id="style-strong-7">
                              Cold-Pressed Juices
                            </p>
                            <p className="box-content min-h-8 block min-w-0 mb-6.5 px-7.5 shrink-0 [font-family:grenette-regular-pro,_stk] text-xl leading-8 tracking-[normal] [overflow-wrap:break-word] [pointer-events:all] max-lg:text-left max-lg:px-0" data-ditto-id="style-link-11">
                              Crafted with premium produce harvested at the peak of freshness, our cold-pressed juices are packed with fresh ingredients and bursting with refreshing flavor.
                            </p>
                            <div className="grid min-w-0 shrink-0 gap-x-5 grid-cols-12 max-lg:flex-col max-lg:gap-y-5 max-lg:grid-cols-1" data-ditto-id="style-strong-8">
                              <div className="flex min-w-0 flex-col basis-[calc(1200%_+_220px)] col-start-[span_12] max-lg:col-start-[span_1] max-lg:basis-[initial]" data-ditto-id="style-link-12">
                                <a className="box-content min-h-5.5 block min-w-0 px-6 rounded-[40px] self-center [justify-self:center] shrink-0 text-background [font-family:FTRegolaNeueBETA-Semibold,_stk] leading-11.5 tracking-[normal] [overflow-wrap:break-word] bg-foreground cursor-pointer [pointer-events:all] max-lg:w-[145.938px]" data-ditto-id="style-br-12" href="https://pressed.com/shop">
                                  Shop Popular Juices
                                </a>
                              </div>
                            </div>
                          </div>
                        </div>
                        <p className="box-content min-h-6 block min-w-0 mb-6.5 col-start-2 [font-family:FTRegolaNeue-Regular,_stk] leading-[1.5625rem] tracking-[normal] [overflow-wrap:break-word] [pointer-events:all]" data-ditto-id="style-link" />
                        <h2 className="box-content min-h-9.5 block min-w-0 mb-3 col-start-2 [font-family:FTRegolaNeue-Regular,_stk] text-[2rem] leading-9.5 tracking-[normal] [overflow-wrap:break-word] [pointer-events:all] max-lg:min-h-7 max-lg:[font-family:FTRegolaNeue-Medium,_stk] max-lg:text-2xl max-lg:leading-7" data-ditto-id="style-div-91" data-component="heading">
                          Cold-Pressed Juice Benefits
                        </h2>
                        {""}
                        <p className="box-content min-h-8 block min-w-0 mb-6.5 col-start-2 [font-family:grenette-regular-pro,_stk] text-xl leading-8 tracking-[normal] [overflow-wrap:break-word] [pointer-events:all]" data-ditto-id="style-figure-11">
                          Here's what makes Pressed cold-pressed juices a step above the rest.
                        </p>
                        <div className="grid min-w-0 mb-6.5 gap-x-5 col-start-2 grid-cols-12 max-lg:flex-col max-lg:gap-y-5 max-lg:grid-cols-1" data-ditto-id="style-div-92">
                          <div className="flex min-w-0 rounded-[20px] flex-col basis-[calc(400%_+_60px)] col-start-[span_4] text-center bg-primary max-lg:col-start-[span_1] max-lg:basis-[initial]" data-ditto-id="style-link-13">
                            <p className="box-content min-h-6 block mb-6.5 shrink-0 [font-family:FTRegolaNeue-Regular,_stk] leading-[1.5625rem] tracking-[normal] [overflow-wrap:break-word] [pointer-events:all]" data-ditto-id="style-image-5" />
                            <figure className="box-content grid relative max-w-full mb-6.5 shrink-0 [overflow-wrap:break-word] [pointer-events:all] grid-cols-1" data-ditto-id="style-div-77">
                              <div className="box-content block col-start-1 row-start-1 overflow-hidden [pointer-events:all]">
                                <img className="box-content w-17 h-[4.6875rem] inline max-w-full aspect-[auto_68/68] align-top [pointer-events:all]" data-ditto-id="style-div-150" data-component="image" height="68" src="/assets/cloned/svg/ab2b99db2137.svg" width="68" />
                              </div>
                            </figure>
                            {""}
                            <p className="box-content min-h-6 block mb-3 shrink-0 [font-family:FTRegolaNeue-Regular,_stk] leading-[1.5625rem] tracking-[normal] [overflow-wrap:break-word] [pointer-events:all]" data-ditto-id="style-div-78">
                              <strong className="box-content min-h-6 inline [font-family:FTRegolaNeue-Semibold,_stk] [pointer-events:all]" data-ditto-id="style-p-6">
                                Nutrient-Dense
                              </strong>
                              {""}
                            </p>
                            <p className="box-content min-h-6 block mb-6.5 px-7.5 shrink-0 [font-family:FTRegolaNeue-Regular,_stk] leading-[1.5625rem] tracking-[normal] [overflow-wrap:break-word] [pointer-events:all]" data-ditto-id="style-div-28">
                              Our blends are made using premium produce, and many of them are high in key vitamins and minerals to help you get the nutritional support you need to power through your day and feel your best from the inside out.
                            </p>
                            <p className="box-content min-h-6 block shrink-0 [font-family:FTRegolaNeue-Regular,_stk] leading-[1.5625rem] tracking-[normal] [overflow-wrap:break-word] [pointer-events:all]" data-ditto-id="style-hr-4" />
                          </div>
                          <div className="flex min-w-0 rounded-[20px] flex-col basis-[calc(400%_+_60px)] col-start-[span_4] text-center bg-primary max-lg:col-start-[span_1] max-lg:basis-[initial]" data-ditto-id="motion-div">
                            <p className="box-content min-h-6 block mb-6.5 shrink-0 [font-family:FTRegolaNeue-Regular,_stk] leading-[1.5625rem] tracking-[normal] [overflow-wrap:break-word] [pointer-events:all]" data-ditto-id="style-p-14" />
                            <figure className="box-content grid relative max-w-full mb-6.5 shrink-0 [overflow-wrap:break-word] [pointer-events:all] grid-cols-1" data-ditto-id="style-div-93">
                              <div className="box-content block col-start-1 row-start-1 overflow-hidden [pointer-events:all]" data-ditto-id="style-div-21">
                                <img className="box-content w-17 h-17 inline max-w-full aspect-[auto_68/68] align-top [pointer-events:all]" data-ditto-id="style-heading-19" data-component="image" height="68" src="/assets/cloned/svg/c498c2a1713f.svg" width="68" />
                              </div>
                            </figure>
                            {""}
                            <p className="box-content min-h-6 block mb-3 shrink-0 [font-family:FTRegolaNeue-Regular,_stk] leading-[1.5625rem] tracking-[normal] [overflow-wrap:break-word] [pointer-events:all]" data-ditto-id="style-strong-37">
                              <strong className="box-content min-h-6 inline [font-family:FTRegolaNeue-Semibold,_stk] [pointer-events:all]" data-ditto-id="style-br-55">
                                Minimal Preservatives
                              </strong>
                            </p>
                            <p className="box-content min-h-6 block px-7.5 shrink-0 [font-family:FTRegolaNeue-Regular,_stk] leading-[1.5625rem] tracking-[normal] [overflow-wrap:break-word] [pointer-events:all]" data-ditto-id="style-div-119">
                              With the exception of vitamin C (ascorbic acid) in some recipes, our juices are made without preservatives, just as nature intended. In fact, we even include a “best by” date on every bottle so you’re sure to enjoy it at peak freshness.
                            </p>
                          </div>
                          <div className="flex min-w-0 rounded-[20px] flex-col basis-[calc(400%_+_60px)] col-start-[span_4] text-center bg-primary max-lg:col-start-[span_1] max-lg:basis-[initial]">
                            <p className="box-content min-h-6 block mb-6.5 shrink-0 [font-family:FTRegolaNeue-Regular,_stk] leading-[1.5625rem] tracking-[normal] [overflow-wrap:break-word] [pointer-events:all]" data-ditto-id="motion-div-2" />
                            <figure className="box-content grid relative max-w-full mb-6.5 shrink-0 [overflow-wrap:break-word] [pointer-events:all] grid-cols-1" data-ditto-id="style-div-79">
                              <div className="box-content block col-start-1 row-start-1 overflow-hidden [pointer-events:all]" data-ditto-id="style-image-15">
                                <img className="box-content w-17 h-14 inline max-w-full aspect-[auto_68/68] align-top [pointer-events:all]" data-ditto-id="style-div-114" data-component="image" height="68" src="/assets/cloned/svg/b41f0e23e649.svg" width="68" />
                              </div>
                            </figure>
                            {""}
                            <p className="box-content min-h-6 block mb-3 shrink-0 [font-family:FTRegolaNeue-Regular,_stk] leading-[1.5625rem] tracking-[normal] [overflow-wrap:break-word] [pointer-events:all]">
                              <strong className="box-content min-h-6 inline [font-family:FTRegolaNeue-Semibold,_stk] [pointer-events:all]" data-ditto-id="style-div-94">
                                Hydraulic Pressed
                              </strong>
                            </p>
                            <p className="box-content min-h-6 block px-7.5 shrink-0 [font-family:FTRegolaNeue-Regular,_stk] leading-[1.5625rem] tracking-[normal] [overflow-wrap:break-word] [pointer-events:all]" data-ditto-id="style-h1">
                              Pressed juices go through a process called HPP (High Pressure Processing). As compared to other processes like pasteurization, HPP helps our product maintain higher nutrient density and minimally impacts vitamins, antioxidants, nutrition, and flavor. It also helps keep our products safe from potential harmful pathogens.
                            </p>
                          </div>
                        </div>
                        <p className="box-content min-h-6 block min-w-0 mb-6.5 col-start-2 [font-family:FTRegolaNeue-Regular,_stk] leading-[1.5625rem] tracking-[normal] [overflow-wrap:break-word] [pointer-events:all]" data-ditto-id="style-strong-38" />
                        <h2 className="box-content min-h-9.5 block min-w-0 mb-6.5 col-start-2 [font-family:FTRegolaNeue-Regular,_stk] text-[2rem] leading-9.5 tracking-[normal] [overflow-wrap:break-word] [pointer-events:all] max-lg:min-h-7 max-lg:[font-family:FTRegolaNeue-Medium,_stk] max-lg:text-2xl max-lg:leading-7" data-ditto-id="style-div-115" data-component="heading">
                          Popular Cold-Pressed Juice Ingredients
                        </h2>
                        {""}
                        <p className="box-content min-h-8 block min-w-0 mb-6.5 col-start-2 [font-family:grenette-regular-pro,_stk] text-xl leading-8 tracking-[normal] [overflow-wrap:break-word] [pointer-events:all]" data-ditto-id="style-div-95">
                          Many of our juices include nutrient-dense leafy greens and fruits that are high in key vitamins. Here are some of our most popular cold-pressed ingredients.
                        </p>
                        <div className="grid min-w-0 mb-6.5 gap-x-5 col-start-2 grid-cols-12 max-lg:flex-wrap max-lg:justify-between max-lg:gap-y-5 max-lg:grid-cols-2" data-ditto-id="style-div-29">
                          {MediaTile_data.map((d, i) => <MediaTile key={i} d={d} styles={MediaTile_styles[i]} />)}
                        </div>
                        <div className="grid min-w-0 mb-6.5 gap-x-5 col-start-2 grid-cols-12 max-lg:flex-wrap max-lg:justify-between max-lg:gap-y-5 max-lg:grid-cols-2" data-ditto-id="style-p-51">
                          {MediaTile2_data.map((d, i) => <MediaTile2 key={i} d={d} styles={MediaTile2_styles[i]} />)}
                        </div>
                        <p className="box-content min-h-6 block min-w-0 mb-6.5 col-start-2 [font-family:FTRegolaNeue-Regular,_stk] leading-[1.5625rem] tracking-[normal] [overflow-wrap:break-word] [pointer-events:all]" data-ditto-id="style-heading-8" />
                        <h2 className="box-content min-h-9.5 block min-w-0 mb-6.5 col-start-2 [font-family:FTRegolaNeue-Regular,_stk] text-[2rem] leading-9.5 tracking-[normal] [overflow-wrap:break-word] [pointer-events:all] max-lg:min-h-7 max-lg:[font-family:FTRegolaNeue-Medium,_stk] max-lg:text-2xl max-lg:leading-7" data-ditto-id="style-div-98" data-component="heading">
                          Cold Pressed Juice FAQs
                        </h2>
                        {""}
                        <hr className="box-content w-255 h-5 min-h-5 flex relative min-w-0 mb-6.5 justify-center items-center col-start-2 text-0 leading-0 tracking-[normal] [overflow-wrap:break-word] [pointer-events:all] max-md:w-[22.8125rem] md:max-lg:w-189.5 before:content-[''] before:block before:w-full before:h-0 before:border-t-[1px] before:border-t-[rgb(0,0,0)]" data-ditto-id="style-div-24" aria-hidden="true" role="presentation" />
                        {""}
                        <h3 className="box-content block min-w-0 mb-6.5 col-start-2 [font-family:FTRegolaNeue-Semibold,_stk] [overflow-wrap:break-word] [pointer-events:all]" data-ditto-id="style-heading-2" data-component="heading">
                          How long is cold-pressed juice good for?
                        </h3>
                        {""}
                        <p className="box-content min-h-6 block min-w-0 mb-6.5 col-start-2 [font-family:FTRegolaNeue-Regular,_stk] leading-[1.5625rem] tracking-[normal] [overflow-wrap:break-word] [pointer-events:all]" data-ditto-id="style-br-13">
                          All Pressed juices, wellness shots and hydration shots are printed with"best by" dates. Our bottles have an imprint of"Best if Used By MM/DD/YY" on the back of the bottle. If you are buying our products at the grocery store, you'll find this date on top of the cap.
                        </p>
                        <hr className="box-content w-255 h-5 min-h-5 flex relative min-w-0 mb-6.5 justify-center items-center col-start-2 text-0 leading-0 tracking-[normal] [overflow-wrap:break-word] [pointer-events:all] max-md:w-[22.8125rem] md:max-lg:w-189.5 before:content-[''] before:block before:w-full before:h-0 before:border-t-[1px] before:border-t-[rgb(0,0,0)]" data-ditto-id="style-br" aria-hidden="true" role="presentation" />
                        {""}
                        <h3 className="box-content block min-w-0 mb-6.5 col-start-2 [font-family:FTRegolaNeue-Semibold,_stk] [overflow-wrap:break-word] [pointer-events:all]" data-ditto-id="style-figure-4" data-component="heading">
                          Why is cold-pressed juice better?
                        </h3>
                        {""}
                        <p className="box-content min-h-6 block min-w-0 mb-6.5 col-start-2 [font-family:FTRegolaNeue-Regular,_stk] leading-[1.5625rem] tracking-[normal] [overflow-wrap:break-word] [pointer-events:all]" data-ditto-id="style-div-15">
                          {"Unlike pasteurized juices, our cold-pressed juices are intended to preserve as many of the produce's nutrients as possible."}
                        </p>
                        <hr className="box-content w-255 h-5 min-h-5 flex relative min-w-0 mb-6.5 justify-center items-center col-start-2 text-0 leading-0 tracking-[normal] [overflow-wrap:break-word] [pointer-events:all] max-md:w-[22.8125rem] md:max-lg:w-189.5 before:content-[''] before:block before:w-full before:h-0 before:border-t-[1px] before:border-t-[rgb(0,0,0)]" data-ditto-id="style-link-14" aria-hidden="true" role="presentation" />
                        {""}
                        <h3 className="box-content block min-w-0 mb-6.5 col-start-2 [font-family:FTRegolaNeue-Semibold,_stk] [overflow-wrap:break-word] [pointer-events:all]" data-ditto-id="style-image-3" data-component="heading">
                          Can I have cold-pressed juice when pregnant?
                        </h3>
                        {""}
                        <p className="box-content min-h-6 block min-w-0 mb-6.5 col-start-2 [font-family:FTRegolaNeue-Regular,_stk] leading-[1.5625rem] tracking-[normal] [overflow-wrap:break-word] [pointer-events:all]" data-ditto-id="style-p-17">
                          Please consult your physician! We use a process called HPP (high pressure processing), so our juices are not raw.
                        </p>
                        <hr className="box-content w-255 h-5 min-h-5 flex relative min-w-0 mb-6.5 justify-center items-center col-start-2 text-0 leading-0 tracking-[normal] [overflow-wrap:break-word] [pointer-events:all] max-md:w-[22.8125rem] md:max-lg:w-189.5 before:content-[''] before:block before:w-full before:h-0 before:border-t-[1px] before:border-t-[rgb(0,0,0)]" data-ditto-id="style-strong-33" aria-hidden="true" role="presentation" />
                        {""}
                        <h3 className="box-content block min-w-0 mb-6.5 col-start-2 [font-family:FTRegolaNeue-Semibold,_stk] [overflow-wrap:break-word] [pointer-events:all]" data-ditto-id="style-p-18" data-component="heading">
                          How long can cold-pressed juice last unrefrigerated?
                        </h3>
                        {""}
                        <p className="box-content min-h-6 block min-w-0 mb-6.5 col-start-2 [font-family:FTRegolaNeue-Regular,_stk] leading-[1.5625rem] tracking-[normal] [overflow-wrap:break-word] [pointer-events:all]" data-ditto-id="style-br-20">
                          Per FDA standards, perishable foods like cold-pressed juices should only be left at room temperature for up to two hours before considered unsafe to consume. However, if the temperature of the room is above 90° F, our products should not be left out of refirgeration for more than one hour.
                        </p>
                        <hr className="box-content w-255 h-5 min-h-5 flex relative min-w-0 mb-6.5 justify-center items-center col-start-2 text-0 leading-0 tracking-[normal] [overflow-wrap:break-word] [pointer-events:all] max-md:w-[22.8125rem] md:max-lg:w-189.5 before:content-[''] before:block before:w-full before:h-0 before:border-t-[1px] before:border-t-[rgb(0,0,0)]" data-ditto-id="style-br-2" aria-hidden="true" role="presentation" />
                        {""}
                        <p className="box-content min-h-6 block min-w-0 mb-6.5 col-start-2 [font-family:FTRegolaNeue-Regular,_stk] leading-[1.5625rem] tracking-[normal] [overflow-wrap:break-word] [pointer-events:all]" data-ditto-id="style-br-21" />
                        <h2 className="box-content min-h-9.5 block min-w-0 mb-3 col-start-2 [font-family:FTRegolaNeue-Regular,_stk] text-[2rem] leading-9.5 tracking-[normal] [overflow-wrap:break-word] [pointer-events:all] max-lg:min-h-7 max-lg:[font-family:FTRegolaNeue-Medium,_stk] max-lg:text-2xl max-lg:leading-7" data-ditto-id="style-br-3" data-component="heading">
                          Learn More About Cold Pressed-Juices
                        </h2>
                        {""}
                        <p className="box-content min-h-6 block min-w-0 col-start-2 [font-family:FTRegolaNeue-Regular,_stk] leading-[1.5625rem] tracking-[normal] [overflow-wrap:break-word] [pointer-events:all]" data-ditto-id="style-link-3" />
                        <div className="grid min-w-0 mb-6.5 gap-x-5 col-start-2 grid-cols-12 max-lg:flex-col max-lg:gap-y-5 max-lg:grid-cols-1" data-ditto-id="style-br-4">
                          <div className="flex min-w-0 flex-col basis-[calc(1200%_+_220px)] col-start-[span_12] max-lg:col-start-[span_1] max-lg:basis-[initial]" data-ditto-id="style-p-19">
                            <div className="h-full grid shrink-0 gap-x-5 grid-cols-12 max-lg:flex-col max-lg:gap-y-5 max-lg:grid-cols-1" data-ditto-id="style-div-16">
                              <div className="flex min-w-0 flex-col basis-[calc(400%_+_60px)] col-start-[span_4] max-lg:col-start-[span_1] max-lg:basis-[initial]" data-ditto-id="style-heading-4">
                                <div className="grid shrink-0 gap-x-5 grid-cols-4 max-lg:flex-col max-lg:gap-y-5 max-lg:grid-cols-1" data-ditto-id="style-br-5">
                                  <div className="border border-solid border-border flex min-w-0 rounded-[10px] flex-col basis-[calc(400%_+_60px)] col-start-[span_4] overflow-hidden max-lg:col-start-[span_1] max-lg:basis-[initial]" data-ditto-id="style-br-14">
                                    <figure className="box-content grid relative max-w-full shrink-0 [overflow-wrap:break-word] [pointer-events:all] grid-cols-1 grid-rows-[calc(2.032vw_+_292.938px)_0px] max-md:grid-rows-[calc(98.259vw_-_11.815px)_0px] md:max-lg:grid-rows-[calc(98.255vw_-_11.799px)_0px]" data-ditto-id="style-figure-3">
                                      <div className="box-content block col-start-1 row-start-1 overflow-hidden [pointer-events:all]" data-ditto-id="style-div-25">
                                        <a className="box-content inline cursor-pointer [pointer-events:all]" data-ditto-id="style-link-15" data-component="link" href="https://pressed.com/blog/how-to-start-juicing-a-beginners-guide">
                                          <img className="box-content w-[20.3125rem] h-80 inline max-w-full aspect-[auto_802/788] align-top [pointer-events:all] max-md:w-[22.6875rem] max-md:h-[22.3125rem] md:max-lg:w-189 md:max-lg:h-[46.4375rem]" data-ditto-id="style-image-6" data-component="image" height="788" src="/assets/cloned/images/a411957ee8b3.jpg" width="802" />
                                        </a>
                                      </div>
                                    </figure>
                                    {""}
                                    <div className="grid shrink-0 gap-x-5 grid-cols-4 max-lg:flex-col max-lg:gap-y-5 max-lg:grid-cols-1" data-ditto-id="style-p-23">
                                      <div className="flex min-w-0 p-6 flex-col basis-[calc(400%_+_60px)] col-start-[span_4] max-lg:col-start-[span_1] max-lg:basis-[initial]" data-ditto-id="style-strong-34">
                                        <p className="box-content min-h-6 block mb-6.5 shrink-0 [font-family:FTRegolaNeue-Regular,_stk] leading-[1.5625rem] tracking-[normal] [overflow-wrap:break-word] [pointer-events:all]" data-ditto-id="style-p-20">
                                          <strong className="box-content min-h-6 inline [font-family:FTRegolaNeue-Semibold,_stk] [pointer-events:all]" data-ditto-id="style-br-6">
                                            <a className="box-content inline cursor-pointer [pointer-events:all]" data-ditto-id="style-br-15" data-component="link" href="https://pressed.com/blog/how-to-start-juicing-a-beginners-guide">
                                              How to Start Juicing: A Beginner's Guide | Pressed™
                                            </a>
                                          </strong>
                                        </p>
                                        <div className="grid shrink-0 gap-x-5 grid-cols-4 max-lg:[grid-auto-columns:1fr]" data-ditto-id="style-br-7">
                                          <div className="flex min-w-0 flex-col basis-[calc(200%_+_20px)] col-start-[span_2] max-lg:row-start-1 max-lg:basis-[initial]" data-ditto-id="style-br-16">
                                            <p className="box-content min-h-6 block shrink-0 [font-family:FTRegolaNeue-Regular,_stk] leading-[1.5625rem] tracking-[normal] [overflow-wrap:break-word] [pointer-events:all]" data-ditto-id="style-link-4">
                                              <a className="box-content inline cursor-pointer [pointer-events:all]" data-ditto-id="style-br-17" data-component="link" href="https://pressed.com/blog/how-to-start-juicing-a-beginners-guide">
                                                Read More
                                              </a>
                                            </p>
                                          </div>
                                          <div className="flex min-w-0 flex-col basis-[calc(200%_+_20px)] col-start-[span_2] max-lg:row-start-1 max-lg:basis-[initial]" data-ditto-id="style-p-10">
                                            <p className="box-content min-h-6 block shrink-0 [font-family:FTRegolaNeue-Regular,_stk] leading-[1.5625rem] tracking-[normal] text-right [overflow-wrap:break-word] [pointer-events:all]" data-ditto-id="style-div-26" />
                                          </div>
                                        </div>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                              </div>
                              <div className="flex min-w-0 flex-col basis-[calc(400%_+_60px)] col-start-[span_4] max-lg:col-start-[span_1] max-lg:basis-[initial]">
                                <div className="grid shrink-0 gap-x-5 grid-cols-4 max-lg:flex-col max-lg:gap-y-5 max-lg:grid-cols-1" data-ditto-id="style-figure-14">
                                  <div className="border border-solid border-border flex min-w-0 rounded-[10px] flex-col basis-[calc(400%_+_60px)] col-start-[span_4] overflow-hidden max-lg:col-start-[span_1] max-lg:basis-[initial]">
                                    <figure className="box-content grid relative max-w-full shrink-0 [overflow-wrap:break-word] [pointer-events:all] grid-cols-1 grid-rows-[calc(2.026vw_+_292.221px)_0px] max-md:grid-rows-[calc(98.006vw_-_11.755px)_0px] md:max-lg:grid-rows-[calc(98.01vw_-_11.765px)_0px]" data-ditto-id="style-link-16">
                                      <div className="box-content block col-start-1 row-start-1 overflow-hidden [pointer-events:all]" data-ditto-id="style-image-16">
                                        <a className="box-content inline cursor-pointer [pointer-events:all]" data-ditto-id="style-p-11" data-component="link" href="https://pressed.com/blog/turmeric-shot-benefits">
                                          <img className="box-content w-[20.3125rem] h-79.5 inline max-w-full aspect-[auto_804/788] align-top [pointer-events:all] max-md:w-[22.6875rem] max-md:h-89 md:max-lg:w-189 md:max-lg:h-[46.3125rem]" data-ditto-id="style-strong-23" data-component="image" height="788" src="/assets/cloned/images/3c828667d3b5.jpg" width="804" />
                                        </a>
                                      </div>
                                    </figure>
                                    {""}
                                    <div className="grid shrink-0 gap-x-5 grid-cols-4 max-lg:flex-col max-lg:gap-y-5 max-lg:grid-cols-1" data-ditto-id="style-p-12">
                                      <div className="flex min-w-0 p-6 flex-col basis-[calc(400%_+_60px)] col-start-[span_4] max-lg:col-start-[span_1] max-lg:basis-[initial]">
                                        <p className="box-content min-h-6 block mb-6.5 shrink-0 [font-family:FTRegolaNeue-Regular,_stk] leading-[1.5625rem] tracking-[normal] [overflow-wrap:break-word] [pointer-events:all]" data-ditto-id="style-br-8">
                                          <strong className="box-content min-h-6 inline [font-family:FTRegolaNeue-Semibold,_stk] [pointer-events:all]" data-ditto-id="style-br-72">
                                            <a className="box-content inline cursor-pointer [pointer-events:all]" data-ditto-id="style-br-9" data-component="link" href="https://pressed.com/blog/turmeric-shot-benefits">
                                              3 Everyday Turmeric Shot Benefits | Pressed™
                                            </a>
                                          </strong>
                                          {""}
                                        </p>
                                        <div className="grid shrink-0 gap-x-5 grid-cols-4 max-lg:[grid-auto-columns:1fr]" data-ditto-id="style-link-5">
                                          <div className="flex min-w-0 flex-col basis-[calc(200%_+_20px)] col-start-[span_2] max-lg:row-start-1 max-lg:basis-[initial]" data-ditto-id="style-br-29">
                                            <p className="box-content min-h-6 block shrink-0 [font-family:FTRegolaNeue-Regular,_stk] leading-[1.5625rem] tracking-[normal] [overflow-wrap:break-word] [pointer-events:all]">
                                              <a className="box-content inline cursor-pointer [pointer-events:all]" data-ditto-id="style-div-56" data-component="link" href="https://pressed.com/blog/turmeric-shot-benefits">
                                                Read More
                                              </a>
                                            </p>
                                          </div>
                                          <div className="flex min-w-0 flex-col basis-[calc(200%_+_20px)] col-start-[span_2] max-lg:row-start-1 max-lg:basis-[initial]">
                                            <p className="box-content min-h-6 block shrink-0 [font-family:FTRegolaNeue-Regular,_stk] leading-[1.5625rem] tracking-[normal] text-right [overflow-wrap:break-word] [pointer-events:all]" data-ditto-id="style-heading-10" />
                                          </div>
                                        </div>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                              </div>
                              <div className="flex min-w-0 flex-col basis-[calc(400%_+_60px)] col-start-[span_4] max-lg:col-start-[span_1] max-lg:basis-[initial]" data-ditto-id="style-heading-11">
                                <div className="grid mb-6.5 shrink-0 gap-x-5 grid-cols-4 max-lg:flex-col max-lg:gap-y-5 max-lg:grid-cols-1" data-ditto-id="style-strong-24">
                                  <div className="border border-solid border-border flex min-w-0 rounded-[10px] flex-col basis-[calc(400%_+_60px)] col-start-[span_4] overflow-hidden max-lg:col-start-[span_1] max-lg:basis-[initial]">
                                    <figure className="box-content grid relative max-w-full shrink-0 [overflow-wrap:break-word] [pointer-events:all] grid-cols-1 grid-rows-[calc(2.026vw_+_293.018px)_0px] max-md:grid-rows-[calc(98.259vw_-_11.815px)_0px] md:max-lg:grid-rows-[calc(98.255vw_-_11.799px)_0px]">
                                      <div className="box-content block col-start-1 row-start-1 overflow-hidden [pointer-events:all]" data-ditto-id="style-p-24">
                                        <a className="box-content inline cursor-pointer [pointer-events:all]" data-ditto-id="style-br-35" data-component="link" href="https://pressed.com/blog/vitamin-c-juices">
                                          <img className="box-content w-[20.3125rem] h-80 inline max-w-full aspect-[auto_802/788] align-top [pointer-events:all] max-md:w-[22.6875rem] max-md:h-[22.3125rem] md:max-lg:w-189 md:max-lg:h-[46.4375rem]" data-ditto-id="style-br-22" data-component="image" height="788" src="/assets/cloned/images/d873f6a596de.jpg" width="802" />
                                        </a>
                                      </div>
                                    </figure>
                                    {""}
                                    <div className="grid shrink-0 gap-x-5 grid-cols-4 max-lg:flex-col max-lg:gap-y-5 max-lg:grid-cols-1" data-ditto-id="style-div-151">
                                      <div className="flex min-w-0 p-6 flex-col basis-[calc(400%_+_60px)] col-start-[span_4] max-lg:col-start-[span_1] max-lg:basis-[initial]" data-ditto-id="style-heading-9">
                                        <p className="box-content min-h-6 block mb-6.5 shrink-0 [font-family:FTRegolaNeue-Regular,_stk] leading-[1.5625rem] tracking-[normal] [overflow-wrap:break-word] [pointer-events:all]" data-ditto-id="style-br-56">
                                          <strong className="box-content min-h-6 inline [font-family:FTRegolaNeue-Semibold,_stk] [pointer-events:all]" data-ditto-id="style-heading-5">
                                            <a className="box-content inline cursor-pointer [pointer-events:all]" data-ditto-id="style-strong-5" data-component="link" href="https://pressed.com/blog/vitamin-c-juices">
                                              4 Delicious Ways to Squeeze More Vitamin C Into Your Day | Pressed™
                                            </a>
                                          </strong>
                                        </p>
                                        <div className="grid shrink-0 gap-x-5 grid-cols-4 max-lg:[grid-auto-columns:1fr]" data-ditto-id="style-p-21">
                                          <div className="flex min-w-0 flex-col basis-[calc(200%_+_20px)] col-start-[span_2] max-lg:row-start-1 max-lg:basis-[initial]" data-ditto-id="style-br-57">
                                            <p className="box-content min-h-6 block shrink-0 [font-family:FTRegolaNeue-Regular,_stk] leading-[1.5625rem] tracking-[normal] [overflow-wrap:break-word] [pointer-events:all]" data-ditto-id="style-br-18">
                                              <a className="box-content inline cursor-pointer [pointer-events:all]" data-ditto-id="style-br-36" data-component="link" href="https://pressed.com/blog/vitamin-c-juices">
                                                Read More
                                              </a>
                                            </p>
                                          </div>
                                          <div className="flex min-w-0 flex-col basis-[calc(200%_+_20px)] col-start-[span_2] max-lg:row-start-1 max-lg:basis-[initial]" data-ditto-id="style-div-99">
                                            <p className="box-content min-h-6 block shrink-0 [font-family:FTRegolaNeue-Regular,_stk] leading-[1.5625rem] tracking-[normal] text-right [overflow-wrap:break-word] [pointer-events:all]" data-ditto-id="style-heading-6" />
                                          </div>
                                        </div>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                                <p className="box-content min-h-6 block shrink-0 [font-family:FTRegolaNeue-Regular,_stk] leading-[1.5625rem] tracking-[normal] [overflow-wrap:break-word] [pointer-events:all]" />
                              </div>
                            </div>
                          </div>
                        </div>
                        {""}
                      </div>
                      {""}
                    </div>
                    {""}
                  </div>
                </div>
              </main>
            </div>
            <footer className="block py-20 text-background bg-foreground max-lg:pt-10 max-lg:pb-16" data-ditto-id="style-heading-18">
              <div className="h-full block" data-ditto-id="style-strong-4">
                <div className="h-full block max-w-360 px-16 mx-auto max-md:px-6 md:max-lg:px-8" data-ditto-id="style-p-53">
                  <div className="border-b border-solid border-b-background grid mb-6 pb-10 gap-x-[5%] grid-cols-[40px_162px_minmax(0,1fr)] max-lg:block max-lg:grid-cols-[40px_162px_auto] max-lg:border-b-[0] max-lg:border-initial max-lg:border-b-[initial] max-lg:pb-0" data-ditto-id="style-br-10">
                    <a className="h-11 block mb-10 cursor-pointer max-lg:inline-block" data-ditto-id="style-br-19" data-component="link" href="/">
                      <img className="w-10 h-10 inline max-w-full overflow-clip" data-ditto-id="style-br-11" data-component="image" alt="Pressed Juicery logo" src={iconFor("Pressed Juicery logo")} />
                    </a>
                    <div className="block" data-ditto-id="style-div-100">
                      <form className="block mb-6" data-ditto-id="style-div-17">
                        <div className="w-full block md:max-lg:w-[61%]" data-ditto-id="style-div-131">
                          <h2 className="block mb-3 [font-family:regola-neue-semibold,_sans-serif] leading-[1.1875rem]" data-ditto-id="style-div-101" data-component="heading">
                            Sign up for our newsletter
                          </h2>
                          <div className="block mb-3 text-sm leading-4" data-ditto-id="style-p-13">
                            Get the latest news and offers by signing up for our newsletter!
                          </div>
                          <div className="block mb-3" aria-label="Enter your email to sign up for our newsletter">
                            <div className="block mb-1 leading-3.5" id="lbl_v-0-0">
                              <label className="inline [font-family:regola-neue-semibold,_sans-serif] leading-6 cursor-default" data-ditto-id="style-div-18" htmlFor="v-0-0">
                                Enter your email
                              </label>
                            </div>
                            <input className="w-full h-10.5 border-2 border-solid border-background block mb-3 py-2 px-4 rounded-[10px] overflow-clip leading-4 tracking-[normal] cursor-text" data-ditto-id="style-p-35" data-component="input" aria-describedby="error_v-0-0" aria-label="Enter your email to sign up for our newsletter" id="v-0-0" />
                          </div>
                          <button className="h-10 border-2 border-solid border-background flex pt-2 pb-3 px-4 rounded-full justify-center items-center leading-[1.125rem] tracking-[normal] text-center whitespace-nowrap bg-foreground cursor-pointer" data-ditto-id="style-heading-12" data-component="button" aria-label="Submit entered email to sign up for our newsletter" role="button" type="submit">
                            {" Sign Up"}
                          </button>
                        </div>
                      </form>
                      <div className="block max-lg:hidden" data-ditto-id="style-strong">
                        <h2 className="block pb-2 [font-family:regola-neue-semibold,_sans-serif]" data-ditto-id="style-p-37" data-component="heading">
                          Get the App
                        </h2>
                        <ul className="grid [list-style-type:none] grid-cols-1" data-ditto-id="style-div-80">
                          <li className="list-item pb-2" data-ditto-id="style-div-19">
                            <a className="inline cursor-pointer" data-ditto-id="style-div-57" data-component="link" href="https://apps.apple.com/us/app/pressed-juicery/id1529648960" rel="noopener" target="_blank">
                              <img className="w-36 h-12 inline max-w-full overflow-clip" data-ditto-id="style-div-69" data-component="image" alt="download from the App Store" src="/assets/cloned/svg/9bccd60d7d6e.svg" />
                            </a>
                          </li>
                          <li className="list-item" data-ditto-id="style-div-20">
                            <a className="inline cursor-pointer" data-ditto-id="style-div-58" data-component="link" href="https://play.google.com/store/apps/details?id=com.pressedjuicery.app" rel="noopener" target="_blank">
                              <img className="w-40.5 h-12 inline max-w-full overflow-clip" data-ditto-id="style-heading-26" data-component="image" alt="download from Google Play" src="/assets/cloned/svg/fbffbc22336d.svg" />
                            </a>
                          </li>
                        </ul>
                      </div>
                    </div>
                    <div className="grid gap-x-[5%] grid-cols-[3249fr_1193fr_1487fr_1106fr_3045fr] max-lg:block max-lg:mb-6 max-lg:grid-cols-[auto_auto_auto_auto_auto]" data-ditto-id="style-br-41">
                      <div className="block max-lg:border-b max-lg:border-solid max-lg:border-b-background max-lg:mb-6 max-lg:pb-6" data-ditto-id="style-br-68">
                        <h2 className="block pb-2 [font-family:regola-neue-semibold,_sans-serif]" data-ditto-id="style-p-61" data-component="heading">
                          Membership
                        </h2>
                        <div className="block pb-4" data-ditto-id="style-div-81">
                          {" Enjoy VIP pricing and earn treats when you subscribe to a Pressed Juicery® Membership."}
                        </div>
                        <a className="inline rounded-xs underline cursor-pointer" data-ditto-id="style-heading-13" data-component="link" href="https://pressed.com/juice-subscription-membership/signup">
                          {" Sign Up"}
                        </a>
                      </div>
                      <div className="block max-lg:border-b max-lg:border-solid max-lg:border-b-background max-lg:mb-6 max-lg:pb-6" data-ditto-id="style-br-69">
                        <h2 className="block pb-2 [font-family:regola-neue-semibold,_sans-serif]" data-ditto-id="style-br-75" data-component="heading">
                          Shop
                        </h2>
                        <ul className="flex flex-col [list-style-type:none] max-lg:flex-wrap max-lg:gap-[4%] max-lg:[flex-direction:initial]" data-ditto-id="style-p-32">
                          {ListRow2_data.map((d, i) => <ListRow2 key={i} d={d} styles={ListRow2_styles[i]} />)}
                        </ul>
                      </div>
                      <div className="block max-lg:border-b max-lg:border-solid max-lg:border-b-background max-lg:mb-6 max-lg:pb-6" data-ditto-id="style-div-71">
                        <h2 className="block pb-2 [font-family:regola-neue-semibold,_sans-serif]" data-component="heading">
                          Learn
                        </h2>
                        <ul className="flex flex-col [list-style-type:none] max-lg:flex-wrap max-lg:gap-[4%] max-lg:[flex-direction:initial]" data-ditto-id="style-div-129">
                          {ListRow3_data.map((d, i) => <ListRow3 key={i} d={d} styles={ListRow3_styles[i]} />)}
                        </ul>
                      </div>
                      <div className="block max-lg:border-b max-lg:border-solid max-lg:border-b-background max-lg:mb-6 max-lg:pb-6" data-ditto-id="style-br-73">
                        <h2 className="block pb-2 [font-family:regola-neue-semibold,_sans-serif]" data-ditto-id="style-p-54" data-component="heading">
                          Support
                        </h2>
                        <ul className="flex flex-col [list-style-type:none] max-lg:flex-wrap max-lg:gap-[4%] max-lg:[flex-direction:initial]" data-ditto-id="style-div-132">
                          {ListRow2_data2.map((d, i) => <ListRow2 key={i} d={d} styles={ListRow2_styles2[i]} />)}
                        </ul>
                      </div>
                      <div className="block max-lg:border-b max-lg:border-solid max-lg:border-b-background max-lg:mb-6 max-lg:pb-6" data-ditto-id="style-p-26">
                        <h2 className="block pb-2 [font-family:regola-neue-semibold,_sans-serif]" data-component="heading">
                          Policies
                        </h2>
                        <ul className="flex flex-col [list-style-type:none] max-lg:flex-wrap max-lg:gap-[4%] max-lg:[flex-direction:initial]" data-ditto-id="style-div-72">
                          {ListRow4_data.map((d, i) => <ListRow4 key={i} d={d} styles={ListRow4_styles[i]} />)}
                        </ul>
                      </div>
                    </div>
                    <div className="hidden min-w-0 max-lg:block max-lg:mb-6 max-lg:justify-between max-lg:items-end" data-ditto-id="style-div-73">
                      <div className="block" data-ditto-id="style-div-142">
                        <h2 className="block pb-2 [font-family:regola-neue-semibold,_sans-serif]" data-ditto-id="style-figure-9">
                          Get the App
                        </h2>
                        <ul className="grid grid-cols-[auto] [list-style-type:none] max-lg:flex max-lg:mb-10 max-lg:items-start" data-ditto-id="style-div-134">
                          <li className="list-item min-w-0 pb-2" data-ditto-id="style-link-18">
                            <a className="inline cursor-pointer max-lg:mr-6" data-ditto-id="style-image-9" href="https://apps.apple.com/us/app/pressed-juicery/id1529648960" rel="noopener" target="_blank">
                              <img className="inline max-w-full overflow-clip max-lg:w-36 max-lg:h-12" data-ditto-id="style-div-74" alt="download from the App Store" src="/assets/cloned/svg/9bccd60d7d6e.svg" />
                            </a>
                          </li>
                          <li className="list-item min-w-0" data-ditto-id="style-heading-21">
                            <a className="inline cursor-pointer max-lg:mr-6" data-ditto-id="style-strong-44" href="https://play.google.com/store/apps/details?id=com.pressedjuicery.app" rel="noopener" target="_blank">
                              <img className="inline max-w-full overflow-clip max-lg:w-40.5 max-lg:h-12" data-ditto-id="style-p-41" alt="download from Google Play" src="/assets/cloned/svg/fbffbc22336d.svg" />
                            </a>
                          </li>
                        </ul>
                      </div>
                      <ul className="hidden [list-style-type:none] max-lg:flex" data-ditto-id="style-strong-45">
                        {Logo2_data.map((d, i) => <Logo2 key={i} d={d} styles={Logo2_styles[i]} />)}
                      </ul>
                    </div>
                  </div>
                  <div className="flex justify-between max-lg:mb-1" data-ditto-id="style-br-48">
                    <div className="flex max-lg:flex-col" data-ditto-id="style-heading-30">
                      <div className="block mr-6 max-lg:mb-2" data-ditto-id="style-strong-26">
                        Ⓒ 2026 Pressed Juicery®
                      </div>
                      <ul className="flex [list-style-type:none] max-lg:flex-col" data-ditto-id="style-p-47">
                        {ListRow5_data.map((d, i) => <ListRow5 key={i} d={d} styles={ListRow5_styles[i]} />)}
                      </ul>
                    </div>
                    <ul className="flex [list-style-type:none] max-lg:hidden" data-ditto-id="style-br-66">
                      {Logo3_data.map((d, i) => <Logo3 key={i} d={d} styles={Logo3_styles[i]} />)}
                    </ul>
                  </div>
                  <div className="block">
                    <a className="inline mr-6 cursor-pointer" data-ditto-id="style-div-68" data-component="link" href="https://pressed.com/legal/sensitive-personal-information-statement">
                      {" Limit the Use of My Sensitive Personal Information"}
                    </a>
                  </div>
                </div>
              </div>
            </footer>
          </div>
        </div>
      </div>
      <div className="block" data-ditto-id="style-div-135" id="teleports" />
      <div className="block" />
      <iframe className="w-px h-px block absolute -top-[624.9375rem] overflow-clip" data-ditto-id="style-div-36" aria-hidden="true" role="presentation" title="Blank" />
      <div className="w-0.5 h-0 block absolute -top-[6249.9375rem] -left-[6249.9375rem] text-0 leading-[normal] whitespace-nowrap" data-ditto-id="style-p-28">
        Mgy
      </div>
      <DropdownMenu menus={[{"trigger":"style-shop-dropdown","hoverOpen":false,"gap":0,"align":"right","html":"<div style=\"position:absolute;margin:0;display:block;box-sizing:border-box;width:304px;height:800px;min-width:0px;max-width:none;min-height:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px;border-top-width:0px;border-right-width:0px;border-bottom-width:0px;border-left-width:0px;border-top-style:none;border-right-style:none;border-bottom-style:none;border-left-style:none;border-top-color:rgb(0, 0, 0);border-right-color:rgb(0, 0, 0);border-bottom-color:rgb(0, 0, 0);border-left-color:rgb(0, 0, 0);border-top-left-radius:0px;border-top-right-radius:0px;border-bottom-right-radius:0px;border-bottom-left-radius:0px;background-color:rgb(255, 255, 255);color:rgb(0, 0, 0);box-shadow:none;opacity:1;font-family:regola-neue-regular, sans-serif;font-size:16px;font-weight:400;font-style:normal;line-height:24px;letter-spacing:0.54px;text-align:start;text-transform:none;text-decoration-line:none;white-space:normal;flex-direction:row;flex-wrap:nowrap;justify-content:normal;align-items:normal;gap:normal;row-gap:normal;column-gap:normal;grid-template-columns:none;grid-template-rows:none;list-style-type:disc;vertical-align:baseline;object-fit:fill;cursor:auto;overflow:auto\"></div>"}]} />
    </>
  );
}
